### PR TITLE
fix(artifacts): Add support for github enterprise

### LINKED ISSUE #2023: Support github enterprise
Right now only github.com is supported. Github enterprise has the same api's for diffs between commits. It should be easy to support if url matching was smarter.

https://github.com/spinnaker/keel/blob/9e228c182c2ac2cc52409512bf79fe6aea3869b0/keel-core/src/main/kotlin/com/netflix/spinnaker/keel/artifacts/ArtifactVersionLinks.kt#L40-L49

https://github.com/spinnaker/keel/blob/9e228c182c2ac2cc52409512bf79fe6aea3869b0/keel-core/src/main/kotlin/com/netflix/spinnaker/keel/artifacts/ArtifactVersionLinks.kt#L61-L69

### PR DESCRIPTION
**Pull request by jessesanford**
Signed-off-by: Jesse Sanford <jesse.sanford@autodesk.com>

Adds support for github enterprise. Currently the gui shows up broken because it doesn't understand URLs that don't contain "github". This will allow those as long as they are "mapped to github" in the list of scm accounts.

### CODE REVIEW

File: keel-core/src/test/kotlin/com/netflix/spinnaker/keel/services/ComparableLinksTests.kt [hunk 1]
```diff
@@ -287,11 +287,11 @@ class ComparableLinksTests : JUnit5Minutests {
         before {
           every { repository.artifactVersions(releaseArtifact, limit) } returns versions.toArtifactVersions(
             releaseArtifact,
-            "stash"
+            "https://stash"
```
Comment (jessesanford) [inline keel-core/src/test/kotlin/com/netflix/spinnaker/keel/services/ComparableLinksTests.kt:290]: Someone please review if it was critical that this work with commit urls that are protocol less. I think that was simply an oversight in writing the test.

Comment (dbyron-sf) [reply keel-core/src/test/kotlin/com/netflix/spinnaker/keel/services/ComparableLinksTests.kt:290]: I don't know the code here to say one way or another, but putting this change in a separate commit would help clarify this....and make it easier to see that tests continue to pass before the other changes in the pr.

Comment (jessesanford) [reply keel-core/src/test/kotlin/com/netflix/spinnaker/keel/services/ComparableLinksTests.kt:290]: Good point. I will restructure this.

Comment (jessesanford) [reply keel-core/src/test/kotlin/com/netflix/spinnaker/keel/services/ComparableLinksTests.kt:290]: Now in explicit commit. Still calling attention to this though here so that it gets eyes :eyes:

File: keel-core/src/main/kotlin/com/netflix/spinnaker/keel/artifacts/ArtifactVersionLinks.kt [hunk 2]
```diff
@@ -35,14 +35,15 @@ class ArtifactVersionLinks(private val scmInfo: ScmInfo, private val cacheFactor
...
-    return if (baseScmUrl != null && olderGitMetadata != null && !(olderGitMetadata.commitInfo?.sha.isNullOrEmpty())) {
+    return if (scmType != null && baseScmUrl != null && olderGitMetadata != null && !(olderGitMetadata.commitInfo?.sha.isNullOrEmpty())) {
       when {
-        "stash" in commitLink -> {
+        "stash" in scmType -> {
           "$baseScmUrl/projects/${newerGitMetadata.project}/repos/${newerGitMetadata.repo?.name}/compare/commits?" +
             "targetBranch=${olderGitMetadata.commitInfo?.sha}&sourceBranch=${newerGitMetadata.commitInfo?.sha}"
         }
-        "github" in commitLink -> {
+        "gitHub" in scmType -> {
```
Comment (nimakaviani) [inline keel-core/src/main/kotlin/com/netflix/spinnaker/keel/artifacts/ArtifactVersionLinks.kt:46]: can we make it case insensitive?

File: keel-core/src/main/kotlin/com/netflix/spinnaker/keel/artifacts/ArtifactVersionLinks.kt [hunk 3]
```diff
@@ -51,22 +52,40 @@ class ArtifactVersionLinks(private val scmInfo: ScmInfo, private val cacheFactor
...
-        scmBaseURLs["stash"]
-      "github" in commitLink -> {
-        val url = URL(scmBaseURLs["gitHub"])
-        "${url.protocol}://${url.host}"
+
+    return if (scmType != null) {
+      when {
+        "stash" in scmType ->
+          scmBaseURLs["stash"]
+        "gitHub" in scmType -> {
```
Comment (nimakaviani) [inline keel-core/src/main/kotlin/com/netflix/spinnaker/keel/artifacts/ArtifactVersionLinks.kt:82]: same here. problably better if `getScmType` converts the type to lower case to ensure consistency.

File: keel-core/src/test/kotlin/com/netflix/spinnaker/keel/services/ComparableLinksTests.kt (hunk 1 above)
Comment (nimakaviani) [reply keel-core/src/test/kotlin/com/netflix/spinnaker/keel/services/ComparableLinksTests.kt:290]: previously, we didnt parse the link to extract the type so https in the source type didnt matter. better version for this change to go is probably here, where the link to the git artifact gets created: https://github.com/spinnaker/keel/blob/cf94218db7fc757c260dd5d866d478857dae0292/keel-core/src/test/kotlin/com/netflix/spinnaker/keel/services/ComparableLinksTests.kt#L157

**Review by nimakaviani — CHANGES_REQUESTED** [review]

File: keel-core/src/main/kotlin/com/netflix/spinnaker/keel/artifacts/ArtifactVersionLinks.kt [hunk 4]
```diff
@@ -51,22 +52,40 @@ class ArtifactVersionLinks(private val scmInfo: ScmInfo, private val cacheFactor
     } else null
   }
 
+  fun getScmType(commitLink: String): String? {
+    val commitURL = URL(commitLink)
```
Comment (nabuskey) [inline keel-core/src/main/kotlin/com/netflix/spinnaker/keel/artifacts/ArtifactVersionLinks.kt:56]: Do we need to worry about the potential exception being thrown here?

File: keel-core/src/main/kotlin/com/netflix/spinnaker/keel/artifacts/ArtifactVersionLinks.kt [hunk 5]
```diff
@@ -51,22 +52,40 @@ class ArtifactVersionLinks(private val scmInfo: ScmInfo, private val cacheFactor
...
+    val scmBaseURLs = runBlocking {
+      val cachedValue = cache[cacheName].get()
+      cachedValue ?: scmInfo.getScmInfo()
+    }
+
+    val base = scmBaseURLs.filter { (_,baseUrl) ->
+      commitURL.host == URL(baseUrl).host
+    }
+
+    return base.keys.toList()[0]
```
Comment (nabuskey) [inline keel-core/src/main/kotlin/com/netflix/spinnaker/keel/artifacts/ArtifactVersionLinks.kt:67]: This could throw index out of boundary exception. If base is not found after filter, we should return null and log.

File: keel-core/src/main/kotlin/com/netflix/spinnaker/keel/artifacts/ArtifactVersionLinks.kt (hunk 2 above)
Comment (jessesanford) [reply keel-core/src/main/kotlin/com/netflix/spinnaker/keel/artifacts/ArtifactVersionLinks.kt]: Yes absolutley.

File: keel-core/src/main/kotlin/com/netflix/spinnaker/keel/artifacts/ArtifactVersionLinks.kt (hunk 3 above)
Comment (jessesanford) [reply keel-core/src/main/kotlin/com/netflix/spinnaker/keel/artifacts/ArtifactVersionLinks.kt]: I would rather perform the normalization of the string closer to the site of the check to avoid ambiguity. Check my latest commits.

File: keel-core/src/main/kotlin/com/netflix/spinnaker/keel/artifacts/ArtifactVersionLinks.kt (hunk 4 above)
Comment (jessesanford) [reply keel-core/src/main/kotlin/com/netflix/spinnaker/keel/artifacts/ArtifactVersionLinks.kt:57]: Yes good call. I didn't like that. I fixed this by using getOrNull.

File: keel-core/src/main/kotlin/com/netflix/spinnaker/keel/artifacts/ArtifactVersionLinks.kt (hunk 5 above)
Comment (jessesanford) [reply keel-core/src/main/kotlin/com/netflix/spinnaker/keel/artifacts/ArtifactVersionLinks.kt]: didn't know about firstOrNull!, but I did use getOrNull let me know if you want me to change it.

File: keel-core/src/test/kotlin/com/netflix/spinnaker/keel/services/ComparableLinksTests.kt (hunk 1 above)
Comment (jessesanford) [reply keel-core/src/test/kotlin/com/netflix/spinnaker/keel/services/ComparableLinksTests.kt:290]: Are you suggesting that we update the mock generation code to convert "stash" -> "https://stash" rather than just use the string literal  "https://stash" below? What is the real world situation? Are these artifacts going to have protocol less sources? I like modifying the literal because the test reads more explicitly.

File: keel-core/src/main/kotlin/com/netflix/spinnaker/keel/artifacts/ArtifactVersionLinks.kt [hunk 6]
```diff
@@ -51,22 +53,41 @@ class ArtifactVersionLinks(private val scmInfo: ScmInfo, private val cacheFactor
...
+    val scmBaseURLs = runBlocking {
+      val cachedValue = cache[cacheName].get()
+      cachedValue ?: scmInfo.getScmInfo()
+    }
+
+    val base = scmBaseURLs.filter { (_,baseUrl) ->
+      commitURL.host == URL(baseUrl).host
+    }
+
+    return base.keys.toList().getOrNull(0)
```
Comment (nimakaviani) [inline keel-core/src/main/kotlin/com/netflix/spinnaker/keel/artifacts/ArtifactVersionLinks.kt:68]: probably slightly easier if `getScmType` return the lowercase type.

```suggestion
    return base.keys.toList().getOrNull(0)?.let { it.lowercase() }
```

File: keel-core/src/main/kotlin/com/netflix/spinnaker/keel/artifacts/ArtifactVersionLinks.kt (hunk 4 above)
Comment (nabuskey) [reply keel-core/src/main/kotlin/com/netflix/spinnaker/keel/artifacts/ArtifactVersionLinks.kt:57]: I was talking about the`java.net.URL` constructor there. It throws `MalformedURLException`. So if given commit link is somehow malformed or empty, the exception will bubble up. `newerGitMetadata?.commitInfo?.link?` will check if it's not null, but not empty / blank string.

File: keel-core/src/main/kotlin/com/netflix/spinnaker/keel/artifacts/ArtifactVersionLinks.kt [hunk 7]
```diff
@@ -51,22 +53,41 @@ class ArtifactVersionLinks(private val scmInfo: ScmInfo, private val cacheFactor
...
     }
-    return when {
-      "stash" in commitLink ->
-        scmBaseURLs["stash"]
-      "github" in commitLink -> {
-        val url = URL(scmBaseURLs["gitHub"])
-        "${url.protocol}://${url.host}"
+
+    return if (scmType != null) {
+      val scmTypeLower = scmType.lowercase()
```
Comment (nimakaviani) [inline keel-core/src/main/kotlin/com/netflix/spinnaker/keel/artifacts/ArtifactVersionLinks.kt:80]:
```suggestion
```

File: keel-core/src/test/kotlin/com/netflix/spinnaker/keel/services/ComparableLinksTests.kt (hunk 1 above)
Comment (nimakaviani) [reply keel-core/src/test/kotlin/com/netflix/spinnaker/keel/services/ComparableLinksTests.kt:290]: yeah either that or have `toArtifactVersions` and the `git` mock receive another optional parameter for `link`. Problem is, the second parameter for `toArtifactVersion` is the source type, and passing the protocol scheme as part of the source type makes it look weird.

Comment (jessesanford) [reply keel-core/src/test/kotlin/com/netflix/spinnaker/keel/services/ComparableLinksTests.kt:290]: I understand what you mean and I agree, however aren't the original github tests passing protocol in via the second parameter? https://github.com/spinnaker/keel/blob/cf94218db7fc757c260dd5d866d478857dae0292/keel-core/src/test/kotlin/com/netflix/spinnaker/keel/services/ComparableLinksTests.kt#L620 should we clean all of these up for consistency in a separate PR?

File: keel-core/src/main/kotlin/com/netflix/spinnaker/keel/artifacts/ArtifactVersionLinks.kt (hunk 6 above)
Comment (jessesanford) [reply keel-core/src/main/kotlin/com/netflix/spinnaker/keel/artifacts/ArtifactVersionLinks.kt:68]: right but per my earlier comment, the intent is less explicit even if is more dry. A compromise could be renaming getScmType to getNormalizedScmType or getLowerScmType, I like the former in case there is more work to normalize these strings in the future.

Comment (nimakaviani) [reply keel-core/src/main/kotlin/com/netflix/spinnaker/keel/artifacts/ArtifactVersionLinks.kt]: yeah lets go with `getNormalizedScmType`. sounds good to me

File: keel-core/src/test/kotlin/com/netflix/spinnaker/keel/services/ComparableLinksTests.kt (hunk 1 above)
Comment (nimakaviani) [reply keel-core/src/test/kotlin/com/netflix/spinnaker/keel/services/ComparableLinksTests.kt:290]: yep, I agree with the inconsistencies, and it is a good idea to fix it while we are at it.

**Comment by nimakaviani** [comment]
build broken? 🤔

**Comment by jessesanford** [comment]
I think we are good to go now. Your requested change can be marked resolved.

**Comment by jessesanford** [comment]
Ok I removed the call to lowercase() because it's still marked as experimental (*shrug*) and instead am using toLowerCase (which is deprecated) but passes the tests. I also found an issue with the normalization that was causing the lookup to fail for github enterprise tests. So I added getScmType back in and dried up the code. Give a look please.

**Comment by jessesanford** [comment]
Ok looks like builds are passing now. @nimakaviani @nabuskey

**Review by nimakaviani — APPROVED** [review]
LGTM
