### PR TITLE
fix(metrics): record drift from last resource check

### LINKED ISSUE #950: Calculate drift metric based on last time resource was checked
The way that keel currently computes the drift metric, when the timeout fires the drift metric resets to zero. This is misleading, because it looks like drift has gone down to zero, even though the time since last resource check is still increasing.

It would be better to change `TelemetryListener` to calculate the drift metric based on the last time a resource was checked, instead of basing it on the start of an actuation loop.

(Suggested by @asher).

### PR DESCRIPTION
**Pull request by lorin**
Calculate the resource check drift metric (keel.resource.check.drift)
by using the last time resource check succeeded as the start time.

Previously, it was calculating based on the beginning of the actuation
loop, which would drop to zero when the loop restarted due to timeout.

Fixes #950

### CODE REVIEW

File: keel-core/src/main/kotlin/com/netflix/spinnaker/keel/actuation/CheckScheduler.kt [hunk 1]
```diff
@@ -79,7 +80,10 @@ class CheckScheduler(
                    * to prevent the cancellation of all coroutines under [job]
                    */
                   withTimeout(checkTimeout.toMillis()) {
-                    launch { resourceActuator.checkResource(it) }
+                    launch {
+                      resourceActuator.checkResource(it)
+                      publisher.publishEvent(ResourceCheckCompleted)
```
Comment (lorin) [inline keel-core/src/main/kotlin/com/netflix/spinnaker/keel/actuation/CheckScheduler.kt:85]: I created a new event that gets published after checkResource completes successfully.

File: keel-core/src/main/kotlin/com/netflix/spinnaker/keel/telemetry/TelemetryListener.kt [hunk 2]
```diff
@@ -115,8 +114,8 @@ class TelemetryListener(
     ).safeIncrement()
   }
 
-  @EventListener(ScheduledResourceCheckStarting::class)
```
Comment (gal-yardeni) [inline keel-core/src/main/kotlin/com/netflix/spinnaker/keel/telemetry/TelemetryListener.kt:118]: Is the new event in addition or instead `ScheduledResourceCheckStarting`?

File: keel-core/src/main/kotlin/com/netflix/spinnaker/keel/actuation/CheckScheduler.kt (hunk 1 above)
Comment (emjburns) [reply keel-core/src/main/kotlin/com/netflix/spinnaker/keel/actuation/CheckScheduler.kt:85]: I think that because this is in a coroutine (`launch {` starts the coroutine in the background) this will publish right when the check starts. It would be worth verifying.

File: keel-core/src/main/kotlin/com/netflix/spinnaker/keel/telemetry/TelemetryEvent.kt [hunk 3]
```diff
@@ -11,6 +11,8 @@ data class ResourceCheckSkipped(
   val skipper: String = "unknown"
 ) : TelemetryEvent()
 
+object ResourceCheckCompleted : TelemetryEvent()
```
Comment (gal-yardeni) [inline keel-core/src/main/kotlin/com/netflix/spinnaker/keel/telemetry/TelemetryEvent.kt:14]: I wonder if `ResourceCheckCompleted` belongs here? is this a `TelemetryEvent` or just an object? if its part of the `TelemetryEvent`, it might be `data class` and not object, and it might need to hold more data, like resource info?

File: keel-core/src/main/kotlin/com/netflix/spinnaker/keel/actuation/CheckScheduler.kt (hunk 1 above)
Comment (lorin) [reply keel-core/src/main/kotlin/com/netflix/spinnaker/keel/actuation/CheckScheduler.kt:85]: @emjburns The `publishEvent` is called after the `checkResource` method returns.

Comment (emjburns) [reply keel-core/src/main/kotlin/com/netflix/spinnaker/keel/actuation/CheckScheduler.kt:85]: ahh 🤦‍♂ great.

File: keel-core/src/main/kotlin/com/netflix/spinnaker/keel/telemetry/TelemetryListener.kt (hunk 2 above)
Comment (lorin) [reply keel-core/src/main/kotlin/com/netflix/spinnaker/keel/telemetry/TelemetryListener.kt:118]: Instead of. Nothing is currently consuming `ScheduledResourceCheckStarting` events. Maybe I should just remove that class altogether.

File: keel-core/src/main/kotlin/com/netflix/spinnaker/keel/telemetry/TelemetryEvent.kt (hunk 3 above)
Comment (lorin) [reply keel-core/src/main/kotlin/com/netflix/spinnaker/keel/telemetry/TelemetryEvent.kt:14]: Good call: I'm going to move it to the file that contains other objects that are used as events but don't have any members.

Comment (lorin) [reply keel-core/src/main/kotlin/com/netflix/spinnaker/keel/telemetry/TelemetryEvent.kt]: Addressed in 5ad23592

File: keel-core/src/main/kotlin/com/netflix/spinnaker/keel/telemetry/TelemetryListener.kt (hunk 2 above)
Comment (lorin) [reply keel-core/src/main/kotlin/com/netflix/spinnaker/keel/telemetry/TelemetryListener.kt:118]: Addressed in 5ad23592

**Comment by lorin** [comment]
rebased against master
