### PR TITLE
fix(actuation) Fix stack overflow in ResourceActuator

### LINKED ISSUE #610: Stack overflow in ResourceActuator
We recently noticed many occurrences of `StackOverflowError` in keel logs.
```
Uncaught exception in thread
java.lang.StackOverflowError: null 	at ch.qos.logback.classic.spi.ThrowableProxy.<init>
(ThrowableProxy.java:54) 	at ch.qos.logback.classic.spi.ThrowableProxy.<init>
(ThrowableProxy.java:60) 	at ch.qos.logback.classic.spi.ThrowableProxy.<init>
(ThrowableProxy.java:60)
```

Investigation notes:

Asher Feldman Yesterday at 7:15 PM
this highlighted log line in ResourceActuator is what’s triggering the stack overflows in main, every time the resource bakery:image:dependency-update-ui is evaluated. Looks like a CannotResolveDesiredState exception that also has a suppressed CannotResolveDesiredState exception with a different cause. The suppressed bit seems to match the issue I shared earlier. I think the coroutine related bits in the suppressed exception are what’s most relevant to the logging bug though

image

21 replies

Asher Feldman  14 hours ago
kotlinx.coroutines.JobCancellationException: Parent job is Cancelling; job=ScopeCoroutine{Cancelled}@4d3691ad is an indicator of an earlier trigger

Asher Feldman  14 hours ago
every time keel calls https://clouddriver-main-readonly.us-west-2.spinnaker.mgmt.netflix.net/aws/images/find?q=dependency-update-ui&account=test (edited) 

Asher Feldman  14 hours ago
java.net.SocketException: Socket closed gets thrown

Rob Fletcher  14 hours ago
Ugh

Asher Feldman  14 hours ago
that clouddriver url loads fine for me via curl or a browser. but every time cloudDriverService.namedImages() is called for dependency-update-ui, socket exception

Asher Feldman  14 hours ago
i can repro locally in keel. i made a different cloudDriverService namedImages method with a String return type in case it was  related to serialization, but that gives me a socket exception too (edited) 

Asher Feldman  14 hours ago
and cloudDriverService.namedImages() is fine when called for anything other than dependency-update-ui

---

Logger bug on circular references in exception classes: https://jira.qos.ch/browse/LOGBACK-1027

### PR DESCRIPTION
**Pull request by luispollo**
Fixes #610.

The root cause for this error was twofold:
1. An `UnknownBaseImage` exception was being thrown here since there were no base images in the config file and the `@ConfigurationProperties` responsible from loading that data into the config properties class had one path too many in the prefix:
  https://github.com/spinnaker/keel/blob/78b9e61498f3a27078cf97f53badab517c92568c/keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/DefaultBaseImageCache.kt#L10

2. The `resolve` extension function defined in `ResourceActuator` was using a [`coroutineScope`](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/coroutine-scope.html) to run the current and desired state evaluations in parallel, which, according to the documentation, has the behavior that "when any child coroutine in this scope fails, this scope fails and all the rest of the children are cancelled". This is why the HTTP requests to clouddriver were being stopped mid-way (socket closed exception) -- when the `UnknownBaseImage` exception was thrown in one child coroutine, the other was forcefully cancelled.
   https://github.com/spinnaker/keel/blob/18d60daf007182401da91dceb08298163b53b999/keel-actuator/src/main/kotlin/com/netflix/spinnaker/keel/actuation/ResourceActuator.kt#L126-L145

I've replaced `coroutineScope` with [`supervisorScope`](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/supervisor-scope.html), where "a failure of a child does not cause this scope to fail and does not affect its other children".

After fixing the coroutine scope issue, I now get this in the logs:
```
{"@timestamp":"2019-12-06T15:59:11.461-08:00","@version":1,"message":"Resource check for bakery:image:server-lab-lpollo failed","logger_name":"com.netflix.spinnaker.keel.actuation.ResourceActuator","thread_name":"DefaultDispatcher-worker-7","level":"ERROR","level_value":40000,"stack_trace":"com.netflix.spinnaker.keel.plugin.CannotResolveDesiredState: Unable to resolve desired state of bakery:image:server-lab-lpollo due to: Could not identify base image for os xenial and label RELEASE\n\tat com.netflix.spinnaker.keel.actuation.ResourceActuator$resolve$2$desired$1.invokeSuspend(ResourceActuator.kt:135)\n\tat kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)\n\tat kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)\n\tat kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)\n\tat kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)\n\tat kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)\nCaused by: com.netflix.spinnaker.keel.bakery.UnknownBaseImage: Could not identify base image for os xenial and label RELEASE\n\tat com.netflix.spinnaker.keel.bakery.DefaultBaseImageCache.getBaseImage(DefaultBaseImageCache.kt:10)\n\tat com.netflix.spinnaker.keel.bakery.resource.ImageHandler.toResolvedType(ImageHandler.kt:56)\n\tat com.netflix.spinnaker.keel.plugin.ResourceHandler.desired(ResourceHandler.kt:79)\n\tat com.netflix.spinnaker.keel.actuation.ResourceActuator.desired(ResourceActuator.kt:181)\n\tat com.netflix.spinnaker.keel.actuation.ResourceActuator$resolve$2$desired$1.invokeSuspend(ResourceActuator.kt:131)\n\t... 5 common frames omitted\n"}
```

Adding the base images to the config file fixes that (now harmless) exception.

### CODE REVIEW

File: keel-actuator/src/main/kotlin/com/netflix/spinnaker/keel/actuation/ResourceActuator.kt [hunk 1]
```diff
@@ -124,7 +124,7 @@ class ResourceActuator(
   }
 
   private suspend fun ResourceHandler<*, *>.resolve(resource: Resource<out ResourceSpec>): Pair<Any, Any?> =
-    coroutineScope {
+    supervisorScope {
```
Comment (luispollo) [inline keel-actuator/src/main/kotlin/com/netflix/spinnaker/keel/actuation/ResourceActuator.kt]: According to the documentation, `coroutineScope`'s behavior is such that "when any child coroutine in this scope fails, this scope fails and all the rest of the children are cancelled". This is why the HTTP requests to clouddriver were being stopped mid-way (socket closed exception) -- when the UnknownBaseImage exception was thrown in one child coroutine, the other was forcefully cancelled.

I've replaced coroutineScope with [supervisorScope](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/supervisor-scope.html), where "a failure of a child does not cause this scope to fail and does not affect its other children".

Comment (emjburns) [reply keel-actuator/src/main/kotlin/com/netflix/spinnaker/keel/actuation/ResourceActuator.kt]: Wow! Good find.

File: keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/DefaultBaseImageCache.kt [hunk 2]
```diff
@@ -10,7 +10,7 @@ class DefaultBaseImageCache(
     baseImages[os]?.get(label.name.toLowerCase()) ?: throw UnknownBaseImage(os, label)
 }
 
-@ConfigurationProperties("keel.plugins.bakery.base-images")
+@ConfigurationProperties(prefix = "keel.plugins.bakery")
```
Comment (luispollo) [inline keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/DefaultBaseImageCache.kt]: There was one path too many in the prefix here, since Spring uses the name of the variable(s) in the class to determine the leaf property name in the config file.

File: keel-actuator/src/main/kotlin/com/netflix/spinnaker/keel/actuation/ResourceActuator.kt (hunk 1 above)
Comment (robfletcher) [reply keel-actuator/src/main/kotlin/com/netflix/spinnaker/keel/actuation/ResourceActuator.kt]: Nice work. Wasn't aware of that option.
