### PR TITLE
fix(events): Fix paused events, again

### LINKED ISSUE #1043: Pausing, deleting a manifest, and then recreating gets keel into a wonky state
Very related to the UX discussion in #780

While one of our internal early adopters was trying things out, they paused their cluster resource to do some things, deleted their test manifest, and then resubmitted a modified manifest. The result of this was that their _new_ cluster resource definition was successfully created, and as a result the resource itself had a single `ResourceCreated` event in the history which led to it getting a `CREATED` status.

Thing is, there was still a row in the pause table for that cluster resource ID. Because of that, keel came around to check the cluster and skipped it because it was paused. This is the behavior I think we'd all want and expect (it seems scary to automatically start actuating something you had previously paused just because you resubmitted it), but because there was no `ResourcePaused` event in event history the resource **appeared** to be stuck in `CREATED`/not working at all, and all the UI / API was effectively making it look like things were totally broken. In order for our team to even understand what was happening we had to look at keel's own logs for that resource ID and discover a bunch of `Actuation for resource <resourceId> is paused, skipping checks` log lines.

Based on what I know about the history event system as it relates to pausing, I have a suspicion that something about the state where a resource is newly created just slips through our existing logic to add a 'synthetic' pause event to the history, which bubbles up to the status being wrong too. Worth also testing out whether application-level pausing has the same experience right now, but given how the UI handles those cases I'm skeptical it suffers from the same problem.

### PR DESCRIPTION
**Pull request by luispollo**
This PR fixes #1043, as follows:
- Revisits the logic in `ActuationPauser` that adds application pause/resume events to resource history by looking _before_ the oldest resource event in the list to see if the application or the resource had been paused and not yet resumed, in which case an `ApplicationActuationPaused` or `ResourceActuationPaused` event with a timestamp matching the time of the pause is added as the last of the events. 

  This is to account for cases where an application or resource is paused, the delivery config subsequently deleted, and then resubmitted before the application or resource is unpaused, in which case the resource status should remain paused.

- Moves business logic around resource status out of `ResourceRepository` and into a new `ResourceHistoryService` bean, which can interact both with repositories as well as other service beans like the `ActuationPauser`.

- Refactors (by moving them into test classes matching the responsible beans) and adds additional tests around resource events and statuses

I've also moved `ApplicationService` out of `keel-web` and into `keel-core`, alongside `ResourceService` for consistency, and simplified its tests so it doesn't depend on `keel-ec2-plugin` by adding easy-to-use new dummy resources with artifacts.

### CODE REVIEW

**Comment by luispollo** [comment]
⚠️ After sleeping on it, I realized my algorithm changes to inject application events won’t work. But I also had an idea that I think can help simplify this whole thing a lot. Will revisit on Monday, stay tuned!

File: keel-core/src/main/kotlin/com/netflix/spinnaker/keel/pause/Pause.kt [hunk 1]
```diff
@@ -0,0 +1,18 @@
+package com.netflix.spinnaker.keel.pause
+
+import java.time.Instant
+
+/**
+ * A pause in an application or resource's actuation, requested by a user.
+ */
+data class Pause(
```
Comment (luispollo) [inline keel-core/src/main/kotlin/com/netflix/spinnaker/keel/pause/Pause.kt:8]: `PausedRepository` now has a corresponding model to work with, like other repositories.

File: keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CombinedRepository.kt [hunk 2]
```diff
@@ -50,7 +52,8 @@ class CombinedRepository(
   val artifactRepository: ArtifactRepository,
   val resourceRepository: ResourceRepository,
   override val clock: Clock,
-  override val publisher: ApplicationEventPublisher
+  override val publisher: ApplicationEventPublisher,
+  override val actuationPauser: ActuationPauser
```
Comment (luispollo) [inline keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CombinedRepository.kt:56]: This is an example of where I see `KeelRepository` and `CombinedRepository` leading us down a path that I don't think is the right one, by creating a "catch-all" bucket where to place service-level functions, which IMHO would be better placed in smaller beans that are focused on specific sub-areas of the domain model (like `ActuationPauser` in this case). Increasingly, I fear we'll start adding dependencies to other service beans here to achieve what we need, and I don't think a "repository" is the right place to be adding that kind of logic. 🤷‍♂️

File: keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CombinedRepository.kt [hunk 3]
```diff
@@ -313,7 +316,10 @@ class CombinedRepository(
     resourceRepository.getResourcesByApplication(application)
 
   override fun getResourceSummaries(deliveryConfig: DeliveryConfig): List<ResourceSummary> =
-    resourceRepository.getResourceSummaries(deliveryConfig)
+    getResourcesByApplication(deliveryConfig.application)
```
Comment (luispollo) [inline keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CombinedRepository.kt:319]: There was no value in adding an additional layer of indirection to get resource summaries from a `ResourceRepository`, plus I needed to use `ActuationPauser` below to determine status (which goes into the summaries), so that logic resides here now.

File: keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/KeelRepository.kt [hunk 4]
```diff
@@ -61,6 +93,13 @@ interface KeelRepository {
       log.debug("Creating $resource")
       storeResource(resource)
       publisher.publishEvent(ResourceCreated(resource, clock))
+
+      // Account for the case where a resource was paused, then deleted (i.e. removed from management), then
```
Comment (luispollo) [inline keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/KeelRepository.kt:97]: Calling attention to this comment.

File: keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/KeelRepository.kt [hunk 5]
```diff
@@ -231,4 +270,108 @@ interface KeelRepository {
...
+  fun getResourceEventHistory(id: String, limit: Int = ResourceRepository.DEFAULT_MAX_EVENTS): List<PersistentEvent> {
+    val resource = getResource(id)
+    return resourceEventHistory(id, limit)
+      .let { events ->
+        actuationPauser.addApplicationActuationEvents(events, resource)
+      }
+  }
+
+  fun getResourceStatus(id: String): ResourceStatus {
+    // For the PAUSED status, we look at the `paused` table as opposed to events, since these records
```
Comment (luispollo) [inline keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/KeelRepository.kt:283]: Calling attention to this comment.

File: keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/KeelRepository.kt [hunk 6]
```diff
@@ -231,4 +270,108 @@ interface KeelRepository {
   ): ArtifactSummaryInEnvironment?
 
   // END ArtifactRepository methods
+
+  fun getResourceEventHistory(id: String, limit: Int = ResourceRepository.DEFAULT_MAX_EVENTS): List<PersistentEvent> {
```
Comment (luispollo) [inline keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/KeelRepository.kt:274]: Functions dealing with resource event history and status now live here, which is the closest place we have at the moment to a service object for these kinds of operations.

File: keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/PausedRepository.kt [hunk 7]
```diff
@@ -17,24 +17,27 @@
...
 
+import com.netflix.spinnaker.keel.pause.Pause
+import com.netflix.spinnaker.keel.pause.PauseScope
+import java.time.Clock
+
 /**
  * A repository to track what scopes are paused, starting with application
  */
 interface PausedRepository {
+  val clock: Clock
```
Comment (luispollo) [inline keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/PausedRepository.kt:28]: The clock is used to timestamp the paused records in the database.

File: keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/PausedRepository.kt [hunk 8]
```diff
@@ -17,24 +17,27 @@
...
+    get() = Clock.systemUTC()
+
+  fun getPause(scope: PauseScope, name: String): Pause?
 
-  fun pauseApplication(application: String)
+  fun pauseApplication(application: String, user: String)
```
Comment (luispollo) [inline keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/PausedRepository.kt:33]: Pause functions now take a user as an argument so we can record that in the database.

File: keel-core/src/main/kotlin/com/netflix/spinnaker/keel/pause/ActuationPauser.kt [hunk 9]
```diff
@@ -66,9 +67,9 @@ class ActuationPauser(
   fun resourceIsPaused(id: String): Boolean =
     pausedRepository.resourcePaused(id)
 
-  fun pauseApplication(application: String) {
+  fun pauseApplication(application: String, user: String) {
```
Comment (luispollo) [inline keel-core/src/main/kotlin/com/netflix/spinnaker/keel/pause/ActuationPauser.kt:70]: Functions that pause things now receive a user as an argument, so we can record who paused them in the database.

File: keel-core/src/main/kotlin/com/netflix/spinnaker/keel/pause/ActuationPauser.kt [hunk 10]
```diff
@@ -102,10 +102,27 @@ class ActuationPauser(
...
+        val oldestResourceEvent = events.last()
+
+        if (oldestResourceEvent is ResourceCreated) {
+          val pause = pausedRepository.getPause(APPLICATION, resource.application)
+          if (pause != null && pause.pausedAt.isBefore(oldestResourceEvent.timestamp)) {
+            // If the app was paused before the resource was created, and hasn't yet been resumed,
+            // we add that event to the history so the resource event history makes sense against its status
+              events.add(ApplicationActuationPaused(resource.application, pause.pausedAt))
+          }
+        }
```
Comment (luispollo) [inline keel-core/src/main/kotlin/com/netflix/spinnaker/keel/pause/ActuationPauser.kt:115]: This is much simplified from my previous attempt. Now that we have timestamps associated with records in the `paused` table, which are _not_ deleted upon deleting delivery configs or resources, we can synthesize paused events in a more straightforward fashion.

File: keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/KeelRepository.kt (hunk 5 above)
Comment (luispollo) [reply keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/KeelRepository.kt:283]: This is the only change in logic in this function and the ones just below. Otherwise, they were just moved over from `ResourceRepository`.

File: keel-core/src/test/kotlin/com/netflix/spinnaker/keel/services/ApplicationServiceTests.kt [hunk 11]
```diff
@@ -1,16 +1,10 @@
-package com.netflix.spinnaker.keel
+package com.netflix.spinnaker.keel.services
```
Comment (luispollo) [inline keel-core/src/test/kotlin/com/netflix/spinnaker/keel/services/ApplicationServiceTests.kt:1]: I removed all dependencies from `ApplicationServiceTests` with the `keel-ec2-plugin` module, which allowed me to move it, and the service class itself, to `keel-core`.

File: keel-sql/src/main/resources/db/changelog/20200427-add-info-to-paused-table.yml [hunk 12]
```diff
@@ -0,0 +1,19 @@
+databaseChangeLog:
+  - changeSet:
+      id: add-timestamp-to-paused-table
+      author: lpollo
+      changes:
+        - addColumn:
+            tableName: paused
+            columns:
+              - column:
+                  name: paused_by
```
Comment (luispollo) [inline keel-sql/src/main/resources/db/changelog/20200427-add-info-to-paused-table.yml:10]: Adds the two new columns that allow us to track who paused things and when.

File: keel-test/src/main/kotlin/com/netflix/spinnaker/keel/test/CombinedRepository.kt [hunk 13]
```diff
@@ -1,30 +1,62 @@
...
-  deliveryConfigRepository: DeliveryConfigRepository = InMemoryDeliveryConfigRepository(clock),
-  artifactRepository: ArtifactRepository = InMemoryArtifactRepository(clock),
-  resourceRepository: ResourceRepository = InMemoryResourceRepository(clock)
-): CombinedRepository =
-  CombinedRepository(deliveryConfigRepository, artifactRepository, resourceRepository, clock, mockk(relaxed = true))
+  deliveryConfigRepository: InMemoryDeliveryConfigRepository = InMemoryDeliveryConfigRepository(clock),
+  artifactRepository: InMemoryArtifactRepository = InMemoryArtifactRepository(clock),
+  resourceRepository: InMemoryResourceRepository = InMemoryResourceRepository(clock),
+  pausedRepository: InMemoryPausedRepository = InMemoryPausedRepository(clock)
+): InMemoryCombinedRepository =
```
Comment (luispollo) [inline keel-test/src/main/kotlin/com/netflix/spinnaker/keel/test/CombinedRepository.kt:50]: This avoids the need to be typecasting things in other places, since everything is explicitly declared as the in-memory type.

File: keel-test/src/main/kotlin/com/netflix/spinnaker/keel/test/CombinedRepository.kt [hunk 14]
```diff
@@ -1,30 +1,62 @@
...
 
 fun combinedMockRepository(
   deliveryConfigRepository: DeliveryConfigRepository = mockk(relaxed = true),
   artifactRepository: ArtifactRepository = mockk(relaxed = true),
   resourceRepository: ResourceRepository = mockk(relaxed = true),
-  clock: Clock = Clock.systemUTC()
+  pausedRepository: PausedRepository = mockk(relaxed = true),
+  clock: Clock = Clock.systemUTC(),
+  publisher: ApplicationEventPublisher = mockk(relaxed = true),
+  actuationPauser: ActuationPauser = ActuationPauser(resourceRepository, pausedRepository, publisher, clock)
```
Comment (luispollo) [inline keel-test/src/main/kotlin/com/netflix/spinnaker/keel/test/CombinedRepository.kt:60]: Another example of where putting service methods in `CombinedRepository` leads to weird patterns. Here, I'm adding a dependency on both `PausedRepository` and to `ActuationPauser` since the latter depends on the former, all so that I can add service methods that can query pause information. I had previously introduced a `ResourceService` that would be a new home for such service methods, but went back on it because I think we need to agree on a path forward as a team before I make further changes of that nature.

File: keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/EventController.kt [hunk 15]
```diff
@@ -34,8 +32,6 @@ class EventController(
     @RequestParam("limit") limit: Int?
   ): List<PersistentEvent> {
     log.debug("Getting state history for: $id")
-    val resource = repository.getResource(id)
-    val events = repository.resourceEventHistory(id, limit ?: DEFAULT_MAX_EVENTS)
-    return actuationPauser.addApplicationActuationEvents(events, resource)
+    return repository.getResourceEventHistory(id, limit ?: DEFAULT_MAX_EVENTS)
```
Comment (luispollo) [inline keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/EventController.kt:35]: Logic to manipulate the resource event history for pauses/resumes is now centralized in `KeelRepository`.

File: keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/ResourceController.kt [hunk 16]
```diff
@@ -66,19 +66,15 @@ class ResourceController(
     and @authorizationSupport.hasCloudAccountPermission('READ', 'RESOURCE', #id)"""
   )
   fun getStatus(@PathVariable("id") id: String): ResourceStatus =
-    if (actuationPauser.isPaused(id)) { // todo eb: we could make determining status easier and more straight forward.
-      PAUSED
-    } else {
-      repository.getResourceStatus(id)
-    }
+    repository.getResourceStatus(id)
```
Comment (luispollo) [inline keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/ResourceController.kt:69]: Logic to determine resource status is now centralized in `KeelRepository`.

File: keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ResourceRepositoryTests.kt [hunk 17]
```diff
@@ -160,18 +158,6 @@ abstract class ResourceRepositoryTests<T : ResourceRepository> : JUnit5Minutests
         test("full resource returned for the application") {
           expectThat(subject.getResourcesByApplication("toast")).hasSize(1)
         }
-
-        test("resource summary is formatted correctly") {
-          val summaries = subject.getResourceSummaries(deliveryConfig)
```
Comment (luispollo) [inline keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ResourceRepositoryTests.kt:165]: Covered by `ResourceServiceTests` now.

File: keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CombinedRepositoryTests.kt [hunk 18]
```diff
@@ -69,24 +70,27 @@ abstract class CombinedRepositoryTests<D : DeliveryConfigRepository, R : Resourc
     environments = setOf(firstEnv)
   )
 
-  data class Fixture<D : DeliveryConfigRepository, R : ResourceRepository, A : ArtifactRepository>(
+  data class Fixture<D : DeliveryConfigRepository, R : ResourceRepository, A : ArtifactRepository, P : PausedRepository>(
```
Comment (luispollo) [inline keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CombinedRepositoryTests.kt:73]: Tests now depend on `PausedRepository` to create an `ActuationPauser`.

File: keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ResourceRepository.kt [hunk 19]
```diff
@@ -161,99 +128,6 @@ interface ResourceRepository : PeriodicallyCheckedRepository<Resource<out Resour
    */
   override fun itemsDueForCheck(minTimeSinceLastCheck: Duration, limit: Int): Collection<Resource<out ResourceSpec>>
 
-  fun getStatus(id: String): ResourceStatus {
```
Comment (luispollo) [inline keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ResourceRepository.kt:164]: Functions moved out of repository and into `ResourceService` bean as per discussions around rethinking responsibility of repositories, in particular not having any "business logic" in them and letting them focus on data-access-related stuff.

File: keel-core/src/main/kotlin/com/netflix/spinnaker/keel/services/ApplicationService.kt [hunk 20]
```diff
@@ -119,19 +118,6 @@ class ApplicationService(
       targetEnvironment = targetEnvironment)
   }
 
-  /**
-   * Returns a list of [ResourceSummary] for the specified application.
-   *
-   * This function assumes there's a single delivery config associated with the application.
-   */
-  fun getResourceSummariesFor(application: String): List<ResourceSummary> =
```
Comment (luispollo) [inline keel-core/src/main/kotlin/com/netflix/spinnaker/keel/services/ApplicationService.kt:127]: Also moved to `ResourceService`.

File: keel-core/src/test/kotlin/com/netflix/spinnaker/keel/veto/UnhappyVetoTests.kt [hunk 21]
```diff
@@ -101,20 +98,6 @@ class UnhappyVetoTests : JUnit5Minutests {
             that(response3.allowed).isFalse()
           }
         }
-
-        test("a happy resource should no longer be skipped ") {
```
Comment (luispollo) [inline keel-core/src/test/kotlin/com/netflix/spinnaker/keel/veto/UnhappyVetoTests.kt:105]: This flow was no longer present in `UnhappyVeto`, in fact `ResouceRepository` was unused there, so I removed the test.

File: keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlResourceRepository.kt [hunk 22]
```diff
@@ -119,24 +117,6 @@ open class SqlResourceRepository(
     }
   }
 
-  override fun getResourceSummaries(deliveryConfig: DeliveryConfig): List<ResourceSummary> {
```
Comment (luispollo) [inline keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlResourceRepository.kt:122]: Moved to `ResourceService`.

File: keel-test/src/main/kotlin/com/netflix/spinnaker/keel/test/Resources.kt [hunk 23]
```diff
@@ -122,6 +123,36 @@ fun <T : ResourceSpec> submittedResource(
     spec = spec
   )
 
+fun versionedArtifactResource(
```
Comment (luispollo) [inline keel-test/src/main/kotlin/com/netflix/spinnaker/keel/test/Resources.kt:126]: New dummy resource types that can be used in tests in `keel-core` where we need artifact info.

File: keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/EventControllerTests.kt [hunk 24]
```diff
@@ -183,100 +177,6 @@ internal class EventControllerTests : JUnit5Minutests {
       }
     }
 
-    context("with application paused at various times") {
```
Comment (luispollo) [inline keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/EventControllerTests.kt:186]: Tests moved to `ResourceServiceTests`.

File: keel-core/src/main/kotlin/com/netflix/spinnaker/keel/services/ResourceService.kt [hunk 25]
```diff
@@ -0,0 +1,192 @@
...
+        actuationPauser.addApplicationActuationEvents(events, resource)
+      }
+  }
+
+  /**
+   * Returns the status of the specified resource by first checking whether or not it or the parent application are
+   * paused, then looking into the last few events in the resource's history.
+   */
+  fun getStatus(id: String): ResourceStatus {
+    // For the PAUSED status, we look at the `paused` table as opposed to events, since these records
```
Comment (luispollo) [inline keel-core/src/main/kotlin/com/netflix/spinnaker/keel/services/ResourceService.kt:73]: Calling attention to this comment. This is the only change in logic in this function and the ones just below. Otherwise, they were just moved over from `ResourceRepository`.

File: keel-core/src/main/kotlin/com/netflix/spinnaker/keel/pause/ActuationPauser.kt [hunk 26]
```diff
@@ -102,10 +102,35 @@ class ActuationPauser(
     mutableListOf<PersistentEvent>()
       .let { events ->
         events.addAll(originalEvents)
-        val relevantAppEvents = resourceRepository
-          .applicationEventHistory(resource.application, events.last().timestamp)
+
+        val oldestResourceEvent = events.last()
+
+        if (oldestResourceEvent is ResourceCreated) {
```
Comment (luispollo) [inline keel-core/src/main/kotlin/com/netflix/spinnaker/keel/pause/ActuationPauser.kt:108]: This is much simplified from my previous attempt. Now that we have timestamps associated with records in the `paused` table (which are not deleted upon deleting delivery configs or resources), we can synthesize paused events in a more straightforward fashion.

File: keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/EventController.kt [hunk 27]
```diff
@@ -34,8 +33,6 @@ class EventController(
     @RequestParam("limit") limit: Int?
   ): List<PersistentEvent> {
     log.debug("Getting state history for: $id")
-    val resource = repository.getResource(id)
-    val events = repository.resourceEventHistory(id, limit ?: DEFAULT_MAX_EVENTS)
-    return actuationPauser.addApplicationActuationEvents(events, resource)
+    return resourceService.getEnrichedEventHistory(id, limit ?: DEFAULT_MAX_EVENTS)
```
Comment (luispollo) [inline keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/EventController.kt:36]: Logic to manipulate the resource event history for pauses/resumes is now centralized in `ResourceService`.

File: keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/ResourceController.kt [hunk 28]
```diff
@@ -66,19 +68,15 @@ class ResourceController(
     and @authorizationSupport.hasCloudAccountPermission('READ', 'RESOURCE', #id)"""
   )
   fun getStatus(@PathVariable("id") id: String): ResourceStatus =
-    if (actuationPauser.isPaused(id)) { // todo eb: we could make determining status easier and more straight forward.
-      PAUSED
-    } else {
-      repository.getResourceStatus(id)
-    }
+    resourceService.getStatus(id)
```
Comment (luispollo) [inline keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/ResourceController.kt:71]: Logic to determine resource status is now centralized in `ResourceService`.

File: keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CombinedRepository.kt (hunk 2 above)
Comment (luispollo) [reply keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CombinedRepository.kt:54]: P.S. If you feel this is not the right place to discuss this, please feel free to add your thoughts in https://github.com/spinnaker/keel/issues/927.

File: keel-core/src/main/kotlin/com/netflix/spinnaker/keel/services/ResourceService.kt [hunk 29]
```diff
@@ -0,0 +1,192 @@
...
+import com.netflix.spinnaker.keel.persistence.ResourceStatus.PAUSED
+import com.netflix.spinnaker.keel.persistence.ResourceStatus.RESUMED
+import com.netflix.spinnaker.keel.persistence.ResourceStatus.UNHAPPY
+import com.netflix.spinnaker.keel.persistence.ResourceStatus.UNKNOWN
+import com.netflix.spinnaker.keel.persistence.ResourceStatus.VETOED
+import org.springframework.stereotype.Component
+
+/**
+ * Service object that offers high-level APIs for resource-related operations.
+ */
```
Comment (emjburns) [inline keel-core/src/main/kotlin/com/netflix/spinnaker/keel/services/ResourceService.kt:49]: It seems like this class deals only with the resource history and status. I think that it makes sense to have a class that deals with those things - they have definitely outgrown living in the `ResourceRepository`. I'd suggest naming this class to reflect that it does those things - I don't think it's a catch-all for resource operations. Maybe `ResourceHistoryService` or `ResourceEventsService`?

I like separating these thing out into their own class because in the future we could decide to change how we do calculate status, and it would be easy to replace that implementation detail in this class.

File: keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/PausedRepository.kt [hunk 30]
```diff
@@ -17,24 +17,27 @@
...
   fun resumeApplication(application: String)
   fun applicationPaused(application: String): Boolean
 
-  fun pauseResource(id: String)
+  fun pauseResource(id: String, user: String)
   fun resumeResource(id: String)
```
Comment (emjburns) [inline keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/PausedRepository.kt:38]: Should resume have the same capturing of user identity?

File: keel-core/src/main/kotlin/com/netflix/spinnaker/keel/services/ApplicationService.kt (hunk 20 above)
Comment (emjburns) [reply keel-core/src/main/kotlin/com/netflix/spinnaker/keel/services/ApplicationService.kt:127]: Why? This is specifically in support of the application summary endpoint, I think it makes sense to stay here with all of the related functions

File: keel-core/src/main/kotlin/com/netflix/spinnaker/keel/services/ResourceService.kt [hunk 31]
```diff
@@ -0,0 +1,192 @@
...
+      // there are other events, we're not thrashing.
+      return false
+    }
+    return true
+  }
+
+  /**
+   * Returns a list of [ResourceSummary] for the specified application.
+   *
+   * This function assumes there's a single delivery config associated with the application.
```
Comment (emjburns) [inline keel-core/src/main/kotlin/com/netflix/spinnaker/keel/services/ResourceService.kt:155]: This comment is not needed, because that's an application-wide assumption

File: keel-core/src/main/kotlin/com/netflix/spinnaker/keel/services/ResourceService.kt [hunk 32]
```diff
@@ -0,0 +1,192 @@
...
+   */
```
Comment (emjburns) [inline keel-core/src/main/kotlin/com/netflix/spinnaker/keel/services/ResourceService.kt:156]: I don't agree that this goes here, but I have a question on the changed implementation. Before this had a sql implementation, now it does not. Is that because you have all the information needed in the delivery config, and we actually didn't need to look in the database?

File: keel-core/src/main/kotlin/com/netflix/spinnaker/keel/pause/ActuationPauser.kt [hunk 33]
```diff
@@ -38,6 +38,7 @@ import org.springframework.stereotype.Component
 
 @Component
 class ActuationPauser(
+  // TODO: replace use of individual repos with KeelRepository
```
Comment (emjburns) [inline keel-core/src/main/kotlin/com/netflix/spinnaker/keel/pause/ActuationPauser.kt:41]: If this only cares about resources, I don't see the need to replace it with the `KeelRepository`

File: keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/KeelRepository.kt (hunk 4 above)
Comment (emjburns) [reply keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/KeelRepository.kt:70]: Wouldn't it be easier to inject the `ApplicationPauser` into the place where we process these events? That way, we don't have to worry about it here, instead we can worry about it when we handle these events.

File: keel-core/src/main/kotlin/com/netflix/spinnaker/keel/veto/unhappy/UnhappyVeto.kt [hunk 34]
```diff
@@ -39,7 +38,6 @@ import org.springframework.stereotype.Component
  */
 @Component
 class UnhappyVeto(
-  private val resourceRepository: ResourceRepository,
```
Comment (emjburns) [inline keel-core/src/main/kotlin/com/netflix/spinnaker/keel/veto/unhappy/UnhappyVeto.kt:42]: was this just leftover and not used anymore?

File: keel-core/src/main/kotlin/com/netflix/spinnaker/keel/pause/Pause.kt [hunk 35]
```diff
@@ -0,0 +1,18 @@
...
+  val scope: PauseScope,
+  val name: String,
```
Comment (gal-yardeni) [inline keel-core/src/main/kotlin/com/netflix/spinnaker/keel/pause/Pause.kt:10]: what does `name` means?

File: keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/KeelRepository.kt (hunk 4 above)
Comment (luispollo) [reply keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/KeelRepository.kt:70]: That's a good idea. I hand't thought about that. Will give it a try.

File: keel-core/src/main/kotlin/com/netflix/spinnaker/keel/services/ResourceService.kt (hunk 29 above)
Comment (luispollo) [reply keel-core/src/main/kotlin/com/netflix/spinnaker/keel/services/ResourceService.kt:49]: Yeah, it's hard to find the right boundaries for these things... I'm not sure having extremely fine-grained service objects (classes with one or two methods) is the best approach either, because you'll end up having to inject a lot of them in other components higher in the stack, like controllers, but I definitely agree that we don't want to create "catch-all" components -- that was my whole rationale for opposing `KeelRepository`.

Let me ask you a question back. You mentioned you liked `ApplicationService`, which started small but now has several more methods. My thinking here was to follow that pattern. What do you think is different in this case that warrants a more narrowly-scoped class versus that case?

Also curious if @robfletcher has any thoughts on this.

File: keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/PausedRepository.kt (hunk 30 above)
Comment (luispollo) [reply keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/PausedRepository.kt:38]: Yes. I initially didn't think of adding it because there's no "resume" table to record it, but this will end up in the events. Was thinking it could be a separate PR since this one is pretty big already...

File: keel-core/src/main/kotlin/com/netflix/spinnaker/keel/services/ResourceService.kt (hunk 31 above)
Comment (luispollo) [reply keel-core/src/main/kotlin/com/netflix/spinnaker/keel/services/ResourceService.kt:155]: Where is the assumption written, though? 🤔

File: keel-core/src/main/kotlin/com/netflix/spinnaker/keel/services/ResourceService.kt (hunk 32 above)
Comment (luispollo) [reply keel-core/src/main/kotlin/com/netflix/spinnaker/keel/services/ResourceService.kt:156]: Correct. It was redundant with the `ResourceRepository.get()` method.

File: keel-core/src/main/kotlin/com/netflix/spinnaker/keel/veto/unhappy/UnhappyVeto.kt (hunk 34 above)
Comment (luispollo) [reply keel-core/src/main/kotlin/com/netflix/spinnaker/keel/veto/unhappy/UnhappyVeto.kt:42]: Correct.

File: keel-core/src/main/kotlin/com/netflix/spinnaker/keel/pause/Pause.kt (hunk 35 above)
Comment (luispollo) [reply keel-core/src/main/kotlin/com/netflix/spinnaker/keel/pause/Pause.kt:10]: The "name" of the thing that was paused (resource or application). It's the name of the column in the database as well. It's more like an identifier, really, but I haven't changed that table, just added the model.

File: keel-core/src/main/kotlin/com/netflix/spinnaker/keel/services/ResourceService.kt (hunk 32 above)
Comment (luispollo) [reply keel-core/src/main/kotlin/com/netflix/spinnaker/keel/services/ResourceService.kt:156]: Correct.

File: keel-core/src/main/kotlin/com/netflix/spinnaker/keel/services/ApplicationService.kt (hunk 20 above)
Comment (luispollo) [reply keel-core/src/main/kotlin/com/netflix/spinnaker/keel/services/ApplicationService.kt:127]: Yeah, I didn't like this either, but the reason I moved it was that the `Resource<*>.toResourceSummary()` extension function has to call `getStatus(id)` for the resource, which, in turn, depends on other beans. Note that this function here was just delegating to `ResourceRepository` previously, where all those other functions used to live.

The alternative was to substitute `resourceService` for `repository` here, but that will introduce a dependency between `ApplicationService` and `ResourceService` which also felt a bit awkward, so I opted for moving it and just injecting both beans into `ApplicationController`.

Happy to undo this if you think the dependency between the two service beans is OK. Or let me know if you have any other ideas!

**Comment by luispollo** [comment]
<video src="https://drive.google.com/file/d/1B9VgLAn0vzIjVvzHjdbssVhIRdWakpXq/preview" width="640" height="480" />

File: keel-core/src/main/kotlin/com/netflix/spinnaker/keel/services/ResourceService.kt (hunk 31 above)
Comment (emjburns) [reply keel-core/src/main/kotlin/com/netflix/spinnaker/keel/services/ResourceService.kt:155]: What do you mean? We have specific checks for it (like [here](https://github.com/spinnaker/keel/blob/master/keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CombinedRepository.kt#L101)), and a unique index constraint on the application field of the delivery config table. If you mean is there text anywhere that says that, I'm not sure, but regardless this comment is not the place to note an application wide assumption

File: keel-core/src/main/kotlin/com/netflix/spinnaker/keel/services/ResourceService.kt (hunk 29 above)
Comment (emjburns) [reply keel-core/src/main/kotlin/com/netflix/spinnaker/keel/services/ResourceService.kt:49]: I think the thing I like about `ApplicationService` is that it is build around a purpose (providing views for the application controller), vs just a collection of application-related methods. It has definitely grown to also include passthroughs for other methods, but the actual logic is all around rendering the views. I'd like to keep that same feeling here with the purpose of doing the event/history things. I don't like the grouping of "resource-related things" because it doesn't seem to have a focused purpose (and is more like the disliked `KeelRepository`).

I also like small and focused classes because they're easier to test and reason about. I don't mind injecting several to do a bigger thing. It's easy to refactor small classes.

File: keel-core/src/main/kotlin/com/netflix/spinnaker/keel/services/ApplicationService.kt (hunk 20 above)
Comment (emjburns) [reply keel-core/src/main/kotlin/com/netflix/spinnaker/keel/services/ApplicationService.kt:127]: Hmm I see. Your original point about the `ApplicationService` was that the controller should be super light, and all the logic should be in the service. I agree with that, and I think based on that reasoning it would make sense to wire in the new history/event service into this class (because you're using that information to generate the application views).

File: keel-core/src/main/kotlin/com/netflix/spinnaker/keel/pause/ActuationPauser.kt [hunk 36]
```diff
@@ -102,10 +102,35 @@ class ActuationPauser(
     mutableListOf<PersistentEvent>()
       .let { events ->
         events.addAll(originalEvents)
-        val relevantAppEvents = resourceRepository
-          .applicationEventHistory(resource.application, events.last().timestamp)
+
+        val oldestResourceEvent = events.last()
```
Comment (gal-yardeni) [inline keel-core/src/main/kotlin/com/netflix/spinnaker/keel/pause/ActuationPauser.kt:105]: watching you explaining it in the video -- I think the name here is a bit confusing since it's not the `oldest` event, it's actually `latest` event, meaning the last event for that application, correct?

**Comment by gal-yardeni** [comment]
@luispollo correct me if I'm wrong, but besides the mega refactoring that you did, the essence of this fix is to inject a synthetic event + timestamp if the application/resource was paused, and keep it paused in case the delivery config gets deleted and recreate?

File: keel-core/src/main/kotlin/com/netflix/spinnaker/keel/pause/ActuationPauser.kt (hunk 36 above)
Comment (luispollo) [reply keel-core/src/main/kotlin/com/netflix/spinnaker/keel/pause/ActuationPauser.kt:105]: Nope, it really is the oldest. The list is ordered in descending order of timestamp, so the first is the newest, and the last is the oldest.

Comment (gal-yardeni) [reply keel-core/src/main/kotlin/com/netflix/spinnaker/keel/pause/ActuationPauser.kt:105]: isn't `events.last` returns the last publish event?

**Comment by luispollo** [comment]
> @luispollo correct me if I'm wrong, but besides the mega refactoring that you did, the essence of this fix is to inject a synthetic event + timestamp if the application/resource was paused, and keep it paused in case the delivery config gets deleted and recreate?

Thanks for the "mega refactoring", haha! 😆 

Yes, I think you got the gist of it. We actually already had code to inject the pause/resume events in history, but we did not account for this case where the delivery config was deleted and then resubmitted, so the focus here is to cater to that case.

File: keel-core/src/main/kotlin/com/netflix/spinnaker/keel/services/ResourceService.kt (hunk 29 above)
Comment (luispollo) [reply keel-core/src/main/kotlin/com/netflix/spinnaker/keel/services/ResourceService.kt:49]: Fair enough. Let's go with `ResourceHistoryService`, then!

File: keel-core/src/main/kotlin/com/netflix/spinnaker/keel/pause/ActuationPauser.kt (hunk 36 above)
Comment (luispollo) [reply keel-core/src/main/kotlin/com/netflix/spinnaker/keel/pause/ActuationPauser.kt:105]: No, that would be `events.first()` because the list is in descending order of timestamp, like I mentioned above.

File: keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/PausedRepository.kt (hunk 30 above)
Comment (luispollo) [reply keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/PausedRepository.kt:38]: I ended up adding this.

**Comment by luispollo** [comment]
@gal-yardeni if it helps, here are the most important bits:

Adding paused events to history on-the-fly based on records in the `event` table:
https://github.com/spinnaker/keel/blob/d56abc35636790a6569e8c43fc0992081b36ccef/keel-core/src/main/kotlin/com/netflix/spinnaker/keel/pause/ActuationPauser.kt#L107-L122

Adding paused event to history when resource is re-created:
https://github.com/spinnaker/keel/blob/d56abc35636790a6569e8c43fc0992081b36ccef/keel-core/src/main/kotlin/com/netflix/spinnaker/keel/events/ResourceHistoryListener.kt#L21-L28

Changing resource status logic to give higher precedence to evaluating paused status based on the `paused` table (not events):
https://github.com/spinnaker/keel/blob/d56abc35636790a6569e8c43fc0992081b36ccef/keel-core/src/main/kotlin/com/netflix/spinnaker/keel/services/ResourceHistoryService.kt#L73-L79

Adding who paused an app/resource and when to the `paused` table:
https://github.com/spinnaker/keel/pull/1069/files#diff-18f7632f0ca5032d4877623591f2322c

Adding who triggered events:
https://github.com/spinnaker/keel/pull/1069/files#diff-2205a5946ca65d2b29a11a32433ed4a6

File: keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/ApplicationController.kt [hunk 37]
```diff
@@ -73,7 +75,7 @@ class ApplicationController(
       }
       entities.forEach { entity ->
         results[entity] = when (entity) {
-          "resources" -> applicationService.getResourceSummariesFor(application)
+          "resources" -> resourceHistoryService.getResourceSummariesFor(application)
```
Comment (emjburns) [inline keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/ApplicationController.kt:78]: I still don't love this but it's fine

Comment (luispollo) [reply keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/ApplicationController.kt:78]: I think I may have misread your previous comments on this. Will add the wrapper function back in `ApplicationService`.

File: keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlResourceRepository.kt [hunk 38]
```diff
@@ -174,7 +174,7 @@ open class SqlResourceRepository(
         .from(EVENT)
         .where(EVENT.SCOPE.eq(Scope.APPLICATION.name))
         .and(EVENT.UID.eq(application))
-        .and(EVENT.TIMESTAMP.lessOrEqual(LocalDateTime.ofInstant(after, ZoneOffset.UTC)))
+        .and(EVENT.TIMESTAMP.greaterOrEqual(LocalDateTime.ofInstant(after, ZoneOffset.UTC)))
```
Comment (luispollo) [inline keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlResourceRepository.kt:177]: This was another bug: the query was backwards! 😱

File: keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/ApplicationController.kt [hunk 39]
```diff
@@ -228,4 +229,14 @@ class ApplicationController(
   ) {
     applicationService.deleteVeto(application, targetEnvironment, reference, version)
   }
+
+  @GetMapping(
+    path = ["/{application}/events"],
```
Comment (luispollo) [inline keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/ApplicationController.kt:234]: I realized we didn't have an endpoint for this and it helps at the very least with testing.

File: keel-core/src/main/kotlin/com/netflix/spinnaker/keel/events/ResourceHistoryListener.kt [hunk 40]
```diff
@@ -1,30 +1,16 @@
...
     resourceRepository.appendHistory(event)
-
-    // Account for the case where a resource was paused, then deleted (i.e. removed from management), then
-    // resubmitted, where we don't want to inadvertently resume actuation without the user knowing and giving
-    // explicit consent, by injecting a ResourceActuationPaused event.
-    // ApplicationActuationPaused events are injected in the resource event history dynamically.
-    if (event is ResourceCreated && actuationPauser.resourceIsPaused(event.id)) {
-      val resource = resourceRepository.get(event.id)
-      resourceRepository.appendHistory(ResourceActuationPaused(resource, resource.serviceAccount, clock))
-    }
```
Comment (luispollo) [inline keel-core/src/main/kotlin/com/netflix/spinnaker/keel/events/ResourceHistoryListener.kt]: This turned out to be redundant with the code I added to `ApplicationPauser`.

File: keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/KeelRepository.kt [hunk 41]
```diff
@@ -132,27 +132,25 @@ interface KeelRepository {
...
   fun getResourcesByApplication(application: String): List<Resource<*>>
 
-  fun getResourceSummaries(deliveryConfig: DeliveryConfig): List<ResourceSummary>
-
   fun storeResource(resource: Resource<*>)
 
   fun deleteResource(id: String)
 
-  fun applicationEventHistory(application: String, limit: Int): List<ApplicationEvent>
+  fun applicationEventHistory(application: String, limit: Int = DEFAULT_MAX_EVENTS): List<ApplicationEvent>
```
Comment (gal-yardeni) [inline keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/KeelRepository.kt:139]: why the `DEFAULT_MAX_EVENTS` was added?

File: keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlResourceRepository.kt (hunk 38 above)
Comment (gal-yardeni) [reply keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlResourceRepository.kt:177]: hmm... didn't we send here the `until` time? how come it used to work?

File: keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/KeelRepository.kt (hunk 41 above)
Comment (luispollo) [reply keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/KeelRepository.kt:139]: Because you can’t query events from the database without a limit, and the controller receives it as a parameter, which needs to be passed down all the way to the repository.

File: keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlResourceRepository.kt (hunk 38 above)
Comment (luispollo) [reply keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlResourceRepository.kt:177]: Yes, I just renamed `until` to `after` for clarity. But it turns out that the query never worked (there wasn’t a test for it, I should probably add one).

Comment (gal-yardeni) [reply keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlResourceRepository.kt:177]: ha I just saw that the only place we use this function is in `ActuationPauser:addApplicationActuationEvents` and you changed the logic there, so I guess it used to work with that query? :)

Comment (luispollo) [reply keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlResourceRepository.kt:177]: No... that's what I meant, I think we just got lucky that there weren't many apps paused, or no one was paying attention to those events being present in the event history. 🤷‍♂️

File: keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/KeelRepository.kt (hunk 41 above)
Comment (luispollo) [reply keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/KeelRepository.kt:139]: Sorry, I misread your comment. We may not need the default here, actually. Let me check.
