### PR TITLE
fix(sql): handle veto when never previously deployed to target environment

### LINKED ISSUE #1086: Veto API (mark as bad) fails with 500 for only one environment (cause unclear)
When posting this payload to `/application/keel/veto`:
```json
{
  "targetEnvironment": "main",
  "reference": "keel",
  "version": "keel-0.498.0~dev.1-h526.48013c1"
}
```
The API returns a 500 with the following stack trace in the logs. The same call worked OK for the `test` and `prestaging` environments. @emjburns had a hunch it may be because the version was never approved for the `main` environment.

```
java.lang.IllegalStateException: jooq
      .select(
    \u2026urn@fetchOne true
      } must not be null
	at com.netflix.spinnaker.keel.sql.SqlArtifactRepository.markAsVetoedIn(SqlArtifactRepository.kt:529)
	at com.netflix.spinnaker.keel.persistence.CombinedRepository.markAsVetoedIn(CombinedRepository.kt:431)
	at com.netflix.spinnaker.keel.persistence.CombinedRepository$$FastClassBySpringCGLIB$$9cfcaa57.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:685)
	at com.netflix.spinnaker.keel.persistence.CombinedRepository$$EnhancerBySpringCGLIB$$54ea4f0f.markAsVetoedIn(<generated>)
	at com.netflix.spinnaker.keel.services.ApplicationService.markAsVetoedIn(ApplicationService.kt:102)
	at com.netflix.spinnaker.keel.rest.ApplicationController.veto(ApplicationController.kt:197)
	at com.netflix.spinnaker.keel.rest.ApplicationController$$FastClassBySpringCGLIB$$1ced6d2b.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:69)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
	at com.netflix.spinnaker.keel.rest.ApplicationController$$EnhancerBySpringCGLIB$$f907237f.veto(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:888)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:118)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at com.netflix.spinnaker.fiat.shared.FiatAuthenticationFilter.doFilter(FiatAuthenticationFilter.java:65)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:158)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:108)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at javax.servlet.FilterChain$doFilter.call(Unknown Source)
	at com.netflix.spinnaker.filters.AuthenticatedRequestFilter.doFilter(AuthenticatedRequestFilter.groovy:143)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:367)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:860)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1598)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```

### PR DESCRIPTION
**Pull request by lorin**
Properly handle the case when vetoing (marking as bad) an artifact version in an environment that had never been deployed to that environment.

Fixes #1086

## Upsert instead of update

Previously, we did an UPDATE to the record in environment_artifact_versions to mark the version as vetoed. This change does an *upsert* instead of an *update*, to handle the case where the record doesn't exist yet.

`updateAsVetoedInEnvironmentArtifactVersionsTable` has been renamed to `upsertAsVetoedInEnvironmentArtifactVersionsTable` to reflect this.

## Don't assume fetchOne always returns a value

Previously, all of the logic in this method was in a lambda passed to the `fetchOne` method. But, because `fetchOne` can return null if there are no matching records, the code inside that lambda wasn't getting executed when the record in environment_artifact_versions didn't exist yet. 

This change moves code out of that lambda.

### CODE REVIEW

File: keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ArtifactRepositoryTests.kt [hunk 1]
```diff
@@ -301,6 +303,27 @@ abstract class ArtifactRepositoryTests<T : ArtifactRepository> : JUnit5Minutests
             get(ArtifactVersionStatus::previous).isEmpty()
           }
         }
+
+        test("an artifact version can be vetoed") {
```
Comment (lorin) [inline keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ArtifactRepositoryTests.kt:307]: I debated putting "and the version has not been promoted to the environment" in the description, but it's already inside of the "No version has been promoted to an environment" context, so I felt that was redundant. But maybe it's better to be explicit?

Comment (gal-yardeni) [reply keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ArtifactRepositoryTests.kt:305]: suggestion: maybe `an artifact version can be vetoed even if it was not previously deployed`?

File: keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlArtifactRepository.kt [hunk 2]
```diff
@@ -591,44 +592,45 @@ class SqlArtifactRepository(
...
-        }
+    /**
+     * If there's a promotion reference, that means this artifact version was deployed as a result of
+     * another artifact version being vetoed. In that case, we don't veto unless [force] is enabled.
+     */
+    selectPromotionReference(envUid, artUid, veto.version)
+      .fetchOne() // null if [veto.version] never made it to the target environment
+      ?.value1() // null if the `promotion_reference` column is NULL
+      ?.let { reference ->
+      if (!force) {
```
Comment (gal-yardeni) [inline keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlArtifactRepository.kt:603]: question: where are we sending this `force`? when can it be false?

File: keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ArtifactRepositoryTests.kt (hunk 1 above)
Comment (lorin) [reply keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ArtifactRepositoryTests.kt]: Fixed in 8400beb

File: keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlArtifactRepository.kt (hunk 2 above)
Comment (lorin) [reply keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlArtifactRepository.kt:603]: Looking through the code, I found two places:

* The [ApplicationController.veto] method, where we set `force=true`
* The [ResourceActuator.checkResource] method, where we don't pass a `force` argument at all, so it uses the default value in [ArtifactRepository.markAsVetoedIn], which is `false`.


[ApplicationController.veto]: https://github.com/spinnaker/keel/blob/master/keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/ApplicationController.kt#L201

[ResourceActuator.checkResource]:
https://github.com/spinnaker/keel/blob/master/keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/ApplicationController.kt#L201

[ArtifactRepository.markAsVetoedIn]:
https://github.com/spinnaker/keel/blob/master/keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ArtifactRepository.kt#L165

Comment (gal-yardeni) [reply keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlArtifactRepository.kt:603]: Thanks! this is super helpful!

File: keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlArtifactRepository.kt [hunk 3]
```diff
@@ -591,44 +592,45 @@ class SqlArtifactRepository(
...
-          }
-        }
+    /**
+     * If there's a promotion reference, that means this artifact version was deployed as a result of
+     * another artifact version being vetoed. In that case, we don't veto unless [force] is enabled.
+     */
+    selectPromotionReference(envUid, artUid, veto.version)
+      .fetchOne() // null if [veto.version] never made it to the target environment
+      ?.value1() // null if the `promotion_reference` column is NULL
+      ?.let { reference ->
```
Comment (luispollo) [inline keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlArtifactRepository.kt:602]: I _think_ you could rewrite this as follows to make it easier to understand:
```suggestion
      .fetchOne(ENVIRONMENT_ARTIFACT_VERSION.REFERENCE)
      ?.let { reference ->
```

Comment (lorin) [reply keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlArtifactRepository.kt:602]: Nice! TIL. 

The suggested change isn't *quite* right (the name of the field is `PROMOTION_REFERENCE`), but I'll apply the suggested change in a commit.

Comment (lorin) [reply keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlArtifactRepository.kt]: Fixed in f05ef40f1
