### PR TITLE
fix(clouddriver): hasAppVersion edge case

### LINKED ISSUE #1052: NoSuchElementException: Collection is empty
We're getting the exception:

```
java.util.NoSuchElementException: Collection is empty.
```

<details><summary>Stack trace</summary>

```
java.util.NoSuchElementException: Collection is empty.
  at kotlin.collections.CollectionsKt___CollectionsKt.first(_Collections.kt:194)
  at com.netflix.spinnaker.keel.clouddriver.model.NamedImageKt.getAppVersion(NamedImage.kt:44)
  at com.netflix.spinnaker.keel.clouddriver.model.NamedImageComparator.compare(NamedImage.kt:17)
  at com.netflix.spinnaker.keel.clouddriver.model.NamedImageComparator.compare(NamedImage.kt:15)
  at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
  at java.util.TimSort.sort(TimSort.java:220)
  at java.util.Arrays.sort(Arrays.java:1438)
  at kotlin.collections.ArraysKt___ArraysJvmKt.sortWith(_ArraysJvm.kt:1959)
  at kotlin.collections.CollectionsKt___CollectionsKt.sortedWith(_Collections.kt:986)
  at com.netflix.spinnaker.keel.clouddriver.ImageService.getLatestNamedImage(ImageService.kt:75)
  at com.netflix.spinnaker.keel.clouddriver.ImageService$getLatestNamedImage$1.invokeSuspend(ImageService.kt:-1)
  at (Coroutine boundary.(:-1)
  at com.netflix.spinnaker.keel.actuation.CheckScheduler$checkArtifacts$job$1$1.invokeSuspend(CheckScheduler.kt:148)
  at com.netflix.spinnaker.keel.actuation.CheckScheduler$checkArtifacts$job$1.invokeSuspend(CheckScheduler.kt:144)

java.util.NoSuchElementException: Collection is empty.
  at kotlin.collections.CollectionsKt___CollectionsKt.first(_Collections.kt:194)
  at com.netflix.spinnaker.keel.clouddriver.model.NamedImageKt.getAppVersion(NamedImage.kt:44)
  at com.netflix.spinnaker.keel.clouddriver.model.NamedImageComparator.compare(NamedImage.kt:17)
  at com.netflix.spinnaker.keel.clouddriver.model.NamedImageComparator.compare(NamedImage.kt:15)
  at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
  at java.util.TimSort.sort(TimSort.java:220)
  at java.util.Arrays.sort(Arrays.java:1438)
  at kotlin.collections.ArraysKt___ArraysJvmKt.sortWith(_ArraysJvm.kt:1959)
  at kotlin.collections.CollectionsKt___CollectionsKt.sortedWith(_Collections.kt:986)
  at com.netflix.spinnaker.keel.clouddriver.ImageService.getLatestNamedImage(ImageService.kt:75)
  at com.netflix.spinnaker.keel.clouddriver.ImageService$getLatestNamedImage$1.invokeSuspend(ImageService.kt:-1)
  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
  at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
  at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

</details>

It looks like the problem is that there is an edge case where `NamedImage.hasAppVersion` returns true even when there is no appversion field in the NamedImage object.

### PR DESCRIPTION
**Pull request by lorin**
## Summary

Fix an edge case in `NamedImage` class where `hasAppVersion` was returning true, even though  app version information was missing.

## Details

Methods in the [ImageService](https://github.com/spinnaker/keel/blob/fa634a154158c6da17cfe0814698dff039fe2bc5/keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/ImageService.kt#L31) class always call `filter{ it.hasAppVersion }` after calling `cloudDriverService.namedImages` , which means that any returned [NamedImage] object should have a valid appversion field.

However, we are seeing an exception being thrown when reading the `NamedImage.appVersion` property (see stack trace in #1052), which shouldn't be possible given that we always filter on `hasAppVersion`. 

It turned out there was a case where the `hasAppVersion` check returns true, even though there's no app version info in the object.

[NamedImage]: https://github.com/spinnaker/keel/blob/d8007d1664b44122651f36234e7d6ed6ef88c921/keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/model/NamedImage.kt#L7

Fixes #1052

### CODE REVIEW

File: keel-clouddriver/src/test/kotlin/com/netflix/spinnaker/keel/clouddriver/model/NamedImageTests.kt [hunk 1]
```diff
@@ -0,0 +1,54 @@
...
+
+        test("does not have an app version") {
+          expectThat(hasAppVersion).isFalse()
+        }
+      }
+      context("empty tagsByImageId") {
+        fixture { makeNamedImage(tagsByImageId = emptyMap()) }
+
+        test("does not have an app version") {
+          expectThat(hasAppVersion).isFalse()
```
Comment (lorin) [inline keel-clouddriver/src/test/kotlin/com/netflix/spinnaker/keel/clouddriver/model/NamedImageTests.kt:49]: This is the case that we were not previously handling correctly.

File: keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/model/NamedImage.kt [hunk 2]
```diff
@@ -34,7 +34,8 @@ val NamedImage.creationDate: Instant
     }
 
 val NamedImage.hasAppVersion: Boolean
-  get() = tagsByImageId
+  get() = tagsByImageId.values.isNotEmpty() &&
+    tagsByImageId
     .values
     .all { it != null && it.containsKey("appversion") }
```
Comment (lorin) [inline keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/model/NamedImage.kt:40]: The problem was the vacuous case: `all` will return true if the collection is empty.

File: keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/model/NamedImage.kt [hunk 3]
```diff
@@ -34,7 +34,8 @@ val NamedImage.creationDate: Instant
     }
 
 val NamedImage.hasAppVersion: Boolean
-  get() = tagsByImageId
+  get() = tagsByImageId.values.isNotEmpty() &&
```
Comment (luispollo) [inline keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/model/NamedImage.kt:37]: I think you could combine the two statements as:
```kotlin
tagsByImageId
  .values
  .let { vals ->
    vals.isNotEmpty() && vals.all { it != null && it.containsKey(“appversion”) }
  }
```

Comment (lorin) [reply keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/model/NamedImage.kt]: Good call. Updated in 5f16c035
