### PR TITLE
fix(logs): Improve logging of error conditions

### LINKED ISSUE #1089: Spike in BadSqlGrammarException and TimeoutCancellationException
There's been a spike in the exceptions above in our logs over the last 12 hours:
image

They seem to always show up in pairs in the logs. Unfortunately, we don't seem to be logging the stack traces anywhere. They appear in the logs as:
```
All keel exceptions should inherit from UserException or SystemException (got org.springframework.jdbc.BadSqlGrammarException). This is a bug.
```
All the messages originate from UI calls:

_messagetime | level | message | x_spinnaker_user_origin
-- | -- | -- | --
05/01/2020 12:13:43.225 -0700 | ERROR | All keel exceptions should inherit from UserException or SystemException (got kotlinx.coroutines.TimeoutCancellationException). This is a bug. | deck
05/01/2020 12:13:43.225 -0700 | ERROR | All keel exceptions should inherit from UserException or SystemException (got org.springframework.jdbc.BadSqlGrammarException). This is a bug. | deck
05/01/2020 12:13:43.225 -0700 | ERROR | All keel exceptions should inherit from UserException or SystemException (got kotlinx.coroutines.TimeoutCancellationException). This is a bug. | deck
05/01/2020 12:13:43.225 -0700 | ERROR | All keel exceptions should inherit from UserException or SystemException (got kotlinx.coroutines.TimeoutCancellationException). This is a bug. | deck
05/01/2020 12:13:43.225 -0700 | ERROR | All keel exceptions should inherit from UserException or SystemException (got kotlinx.coroutines.TimeoutCancellationException). This is a bug. | deck

@emjburns suspected they may still be a result of the incident we had on 4/28 that put keel in a bad state, including some of the data in the database.

### PR DESCRIPTION
**Pull request by luispollo**
Closes #1089 and adds other small improvements to logs for error conditions. More details in inline comments.

### CODE REVIEW

File: keel-core/src/main/kotlin/com/netflix/spinnaker/keel/actuation/ResourceActuator.kt [hunk 1]
```diff
@@ -171,7 +171,7 @@ class ResourceActuator(
           }
         }
       } catch (e: ResourceCurrentlyUnresolvable) {
-        log.warn("Resource check for {} failed (hopefully temporarily) due to {}", id, e.message)
+        log.warn("Resource check for {} failed (hopefully temporarily) due to {}", id, e.message, e)
```
Comment (luispollo) [inline keel-core/src/main/kotlin/com/netflix/spinnaker/keel/actuation/ResourceActuator.kt:174]: Ensure stack trace is logged in this case, so that exception is captured by our exception monitoring system.

File: keel-core/src/main/kotlin/com/netflix/spinnaker/keel/events/ResourceEvent.kt [hunk 2]
```diff
@@ -385,14 +385,14 @@ enum class ResourceCheckErrorOrigin {
...
-        SystemException::class.java.isAssignableFrom(exceptionType) -> SYSTEM
+    val log: Logger by lazy { LoggerFactory.getLogger(ResourceCheckErrorOrigin.javaClass) }
+    fun fromException(exception: SpinnakerException) =
+      when (exception) {
+        is UserException -> USER
+        is SystemException -> SYSTEM
         else -> UNKNOWN.also {
-          log.error("All keel exceptions should inherit from UserException or SystemException (got ${exceptionType.name}). " +
-            "This is a bug.")
+          log.debug("All keel exceptions should inherit from UserException or SystemException (got ${exception.javaClass.name}). " +
```
Comment (luispollo) [inline keel-core/src/main/kotlin/com/netflix/spinnaker/keel/events/ResourceEvent.kt:394]: Lowering the log severity here so it doesn't get mistaken for errors or, worse, trigger alerts from the exception monitoring system.

File: keel-core/src/main/kotlin/com/netflix/spinnaker/keel/events/ResourceEvent.kt [hunk 3]
```diff
@@ -385,14 +385,14 @@ enum class ResourceCheckErrorOrigin {
...
+            "This is a probably a bug.")
```
Comment (luispollo) [inline keel-core/src/main/kotlin/com/netflix/spinnaker/keel/events/ResourceEvent.kt:395]: "Probably" because, although it's certainly a bug for new events thrown after the introduction of this check, this code path is also used when instantiating old events from the database.

File: keel-core/src/main/kotlin/com/netflix/spinnaker/keel/exceptions/InvalidRegexException.kt [hunk 4]
```diff
@@ -31,4 +31,4 @@ class InvalidRegexException(
 class NoDockerImageSatisfiesConstraints(
   val artifactName: String,
   val environment: String
-) : ResourceCurrentlyUnresolvable("No docker image found for artifact $artifactName in $environment")
+) : ResourceCurrentlyUnresolvable("No docker image found for artifact $artifactName that satisfies constraints in environment $environment")
```
Comment (luispollo) [inline keel-core/src/main/kotlin/com/netflix/spinnaker/keel/exceptions/InvalidRegexException.kt:34]: Use the same language as for AMIs to make clear the problem is not that an image was not found, but that no image that satisfies constraints was found.
https://github.com/spinnaker/keel/blob/08289eb264e33538c8630003d059343504843845/keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/NoImageFound.kt#L28-L29

File: keel-core/src/main/kotlin/com/netflix/spinnaker/keel/events/ResourceEvent.kt [hunk 5]
```diff
@@ -385,14 +385,14 @@ enum class ResourceCheckErrorOrigin {
   @JsonProperty("unknown") UNKNOWN;
 
   companion object {
-    val log: Logger by lazy { LoggerFactory.getLogger(javaClass) }
-    fun fromException(exceptionType: Class<out SpinnakerException>) =
-      when {
-        UserException::class.java.isAssignableFrom(exceptionType) -> USER
-        SystemException::class.java.isAssignableFrom(exceptionType) -> SYSTEM
+    val log: Logger by lazy { LoggerFactory.getLogger(ResourceCheckErrorOrigin.javaClass) }
```
Comment (emjburns) [inline keel-core/src/main/kotlin/com/netflix/spinnaker/keel/events/ResourceEvent.kt:388]: switch in logger class so that it shows up more sanely?
