### PR TITLE
fix(configName): check delivery config name uniqueness

### LINKED ISSUE #1260: Submitting a delivery config with conflicting name leaves apps in bad state
I submitted this delivery config to the API:
```yaml
name: mddemotitus
application: lpollomdtest
serviceAccount: delivery-engineering@netflix.com
artifacts:
  - name: spkr/mddemo-titus
    type: docker
    tagVersionStrategy: branch-job-commit-by-job
    reference: mddemo-titus
environments:
  - name: test
    constraints:
      - type: manual-judgement
    notifications:
      - type: slack
        address: "#luis-test"
        frequency: quiet
    resources:
      - kind: "titus/cluster@v1"
        metadata: {}
        spec:
          moniker:
            app: lpollomdtest
            stack: test
          deployWith:
            strategy: "red-black"
          locations:
            account: "titustestvpc"
            vpc: "vpc0"
            regions:
              - name: "us-east-1"
          overrides: {}
          container:
            reference: mddemo-titus
          constraints:
            hard: {}
            soft: {}
          dependencies:
            securityGroupNames:
              - "nf-infrastructure"
              - "nf-datacenter"
              - "mddemotitus"
          iamProfile: "TitusContainerDefaultRole"
```
There was an existing `mddemotitus` delivery config in the database, associated with a different application. The call succeeded, and the result was that neither application seems to have managed resources:

image

image

The API response from the Environments view for `lpollomdtest` is as follows:
```json
{
  "applicationPaused": false,
  "hasManagedResources": true,
  "currentEnvironmentConstraints": [],
  "resources": [],
  "artifacts": [],
  "environments": []
}
```
And for `mddemotitus`:
<details><summary>Click to expand</summary>

```json
{
  "applicationPaused": false,
  "hasManagedResources": false,
  "currentEnvironmentConstraints": [
    {
      "deliveryConfigName": "mddemotitus",
      "environmentName": "test",
      "artifactVersion": "master-h19.fa3d725",
      "type": "manual-judgement",
      "status": "PENDING",
      "createdAt": "2020-06-01T23:29:41.250Z"
    }
  ],
  "resources": [
    {
      "id": "titus:cluster:titustestvpc:lpollomdtest-test",
      "kind": "titus/cluster@v1",
      "status": "ACTUATING",
      "moniker": {
        "app": "lpollomdtest",
        "stack": "test"
      },
      "locations": {
        "account": "titustestvpc",
        "vpc": "vpc0",
        "regions": [
          {
            "name": "us-east-1"
          }
        ]
      },
      "artifact": {
        "name": "spkr/mddemo-titus",
        "type": "docker",
        "reference": "mddemo-titus"
      }
    }
  ],
  "artifacts": [
    {
      "name": "spkr/mddemo-titus",
      "type": "docker",
      "reference": "mddemo-titus",
      "versions": [
        {
          "version": "master-h20.fa3d725",
          "displayName": "master-h20.fa3d725",
          "environments": [
            {
              "name": "test",
              "state": "vetoed",
              "deployedAt": "2020-06-01T23:28:44.826Z",
              "replacedAt": "2020-06-01T23:17:38.189Z",
              "replacedBy": "master-h18.fa3d725",
              "isPinned": false,
              "statefulConstraints": [
                {
                  "type": "manual-judgement",
                  "status": "PENDING",
                  "startedAt": "2020-06-01T23:17:37.597Z"
                }
              ]
            }
          ],
          "build": {
            "id": 20
          },
          "git": {
            "commit": "fa3d725"
          }
        },
        {
          "version": "master-h19.fa3d725",
          "displayName": "master-h19.fa3d725",
          "environments": [
            {
              "name": "test",
              "state": "deploying",
              "deployedAt": "2020-06-01T23:34:46.802Z",
              "replacedAt": "2020-06-01T19:58:04.201Z",
              "replacedBy": "master-h20.fa3d725",
              "isPinned": false,
              "statefulConstraints": [
                {
                  "type": "manual-judgement",
                  "status": "PENDING",
                  "startedAt": "2020-06-01T23:29:41.250Z"
                }
              ]
            }
          ],
          "build": {
            "id": 19
          },
          "git": {
            "commit": "fa3d725"
          }
        },
        {
          "version": "master-h18.fa3d725",
          "displayName": "master-h18.fa3d725",
          "environments": [
            {
              "name": "test",
              "state": "previous",
              "deployedAt": "2020-06-01T23:17:38.188Z",
              "replacedAt": "2020-06-01T23:20:40.256Z",
              "replacedBy": "master-h20.fa3d725",
              "isPinned": false,
              "statefulConstraints": [
                {
                  "type": "manual-judgement",
                  "status": "NOT_EVALUATED"
                }
              ]
            }
          ],
          "build": {
            "id": 18
          },
          "git": {
            "commit": "fa3d725"
          }
        },
        {
          "version": "master-h17.fa3d725",
          "displayName": "master-h17.fa3d725",
          "environments": [
            {
              "name": "test",
              "state": "previous",
              "deployedAt": "2020-05-20T00:59:28.238Z",
              "replacedAt": "2020-05-27T20:20:15.591Z",
              "replacedBy": "master-h18.fa3d725",
              "isPinned": false,
              "statefulConstraints": [
                {
                  "type": "manual-judgement",
                  "status": "NOT_EVALUATED"
                }
              ]
            }
          ],
          "build": {
            "id": 17
          },
          "git": {
            "commit": "fa3d725"
          }
        },
        {
          "version": "master-h16.fa3d725",
          "displayName": "master-h16.fa3d725",
          "environments": [
            {
              "name": "test",
              "state": "previous",
              "deployedAt": "2020-05-18T21:21:26.502Z",
              "replacedAt": "2020-05-20T00:59:28.241Z",
              "replacedBy": "master-h17.fa3d725",
              "isPinned": false,
              "statefulConstraints": [
                {
                  "type": "manual-judgement",
                  "status": "NOT_EVALUATED"
                }
              ]
            }
          ],
          "build": {
            "id": 16
          },
          "git": {
            "commit": "fa3d725"
          }
        },
        {
          "version": "master-h15.0a3ef3e",
          "displayName": "master-h15.0a3ef3e",
          "environments": [
            {
              "name": "test",
              "state": "previous",
              "deployedAt": "2020-05-11T19:53:56.773Z",
              "replacedAt": "2020-05-11T19:56:57.916Z",
              "replacedBy": "master-h16.fa3d725",
              "isPinned": false,
              "statefulConstraints": [
                {
                  "type": "manual-judgement",
                  "status": "NOT_EVALUATED"
                }
              ]
            }
          ],
          "build": {
            "id": 15
          },
          "git": {
            "commit": "0a3ef3e"
          }
        },
        {
          "version": "master-h14.8cabcd6",
          "displayName": "master-h14.8cabcd6",
          "environments": [
            {
              "name": "test",
              "state": "previous",
              "deployedAt": "2020-05-18T20:52:17.218Z",
              "replacedAt": "2020-05-18T21:21:26.504Z",
              "replacedBy": "master-h16.fa3d725",
              "isPinned": false,
              "statefulConstraints": [
                {
                  "type": "manual-judgement",
                  "status": "NOT_EVALUATED"
                }
              ]
            }
          ],
          "build": {
            "id": 14
          },
          "git": {
            "commit": "8cabcd6"
          }
        },
        {
          "version": "master-h13.53888a8",
          "displayName": "master-h13.53888a8",
          "environments": [
            {
              "name": "test",
              "state": "previous",
              "deployedAt": "2020-04-10T19:44:12.436Z",
              "replacedAt": "2020-04-10T19:47:13.347Z",
              "replacedBy": "master-h14.8cabcd6",
              "isPinned": false,
              "statefulConstraints": [
                {
                  "type": "manual-judgement",
                  "status": "NOT_EVALUATED"
                }
              ]
            }
          ],
          "build": {
            "id": 13
          },
          "git": {
            "commit": "53888a8"
          }
        },
        {
          "version": "master-h12.1100b8b",
          "displayName": "master-h12.1100b8b",
          "environments": [
            {
              "name": "test",
              "state": "previous",
              "deployedAt": "2020-04-08T20:20:07.958Z",
              "replacedAt": "2020-04-10T19:44:12.438Z",
              "replacedBy": "master-h13.53888a8",
              "isPinned": false,
              "statefulConstraints": [
                {
                  "type": "manual-judgement",
                  "status": "NOT_EVALUATED"
                }
              ]
            }
          ],
          "build": {
            "id": 12
          },
          "git": {
            "commit": "1100b8b"
          }
        },
        {
          "version": "master-h11.1100b8b",
          "displayName": "master-h11.1100b8b",
          "environments": [
            {
              "name": "test",
              "state": "previous",
              "deployedAt": "2020-04-08T18:33:31.194Z",
              "replacedAt": "2020-04-08T18:40:31.364Z",
              "replacedBy": "master-h12.1100b8b",
              "isPinned": false,
              "statefulConstraints": [
                {
                  "type": "manual-judgement",
                  "status": "NOT_EVALUATED"
                }
              ]
            }
          ],
          "build": {
            "id": 11
          },
          "git": {
            "commit": "1100b8b"
          }
        },
        {
          "version": "master-h10.96eef56",
          "displayName": "master-h10.96eef56",
          "environments": [
            {
              "name": "test",
              "state": "previous",
              "deployedAt": "2020-03-27T18:41:19.391Z",
              "isPinned": false,
              "statefulConstraints": [
                {
                  "type": "manual-judgement",
                  "status": "NOT_EVALUATED"
                }
              ]
            }
          ],
          "build": {
            "id": 10
          },
          "git": {
            "commit": "96eef56"
          }
        },
        {
          "version": "master-h9.8377d7a",
          "displayName": "master-h9.8377d7a",
          "environments": [
            {
              "name": "test",
              "state": "previous",
              "deployedAt": "2020-03-27T18:38:20.024Z",
              "isPinned": false,
              "statefulConstraints": [
                {
                  "type": "manual-judgement",
                  "status": "NOT_EVALUATED"
                }
              ]
            }
          ],
          "build": {
            "id": 9
          },
          "git": {
            "commit": "8377d7a"
          }
        },
        {
          "version": "master-h8.930f489",
          "displayName": "master-h8.930f489",
          "environments": [
            {
              "name": "test",
              "state": "previous",
              "deployedAt": "2020-03-27T18:29:17.291Z",
              "isPinned": false,
              "statefulConstraints": [
                {
                  "type": "manual-judgement",
                  "status": "NOT_EVALUATED"
                }
              ]
            }
          ],
          "build": {
            "id": 8
          },
          "git": {
            "commit": "930f489"
          }
        },
        {
          "version": "master-h7.390b218",
          "displayName": "master-h7.390b218",
          "environments": [
            {
              "name": "test",
              "state": "previous",
              "deployedAt": "2020-03-05T04:51:36Z",
              "isPinned": false,
              "statefulConstraints": [
                {
                  "type": "manual-judgement",
                  "status": "NOT_EVALUATED"
                }
              ]
            }
          ],
          "build": {
            "id": 7
          },
          "git": {
            "commit": "390b218"
          }
        },
        {
          "version": "master-h6.63e586e",
          "displayName": "master-h6.63e586e",
          "environments": [
            {
              "name": "test",
              "state": "previous",
              "deployedAt": "2020-02-12T21:53:32Z",
              "isPinned": false,
              "statefulConstraints": [
                {
                  "type": "manual-judgement",
                  "status": "NOT_EVALUATED"
                }
              ]
            }
          ],
          "build": {
            "id": 6
          },
          "git": {
            "commit": "63e586e"
          }
        },
        {
          "version": "master-h5.46cd7bf",
          "displayName": "master-h5.46cd7bf",
          "environments": [
            {
              "name": "test",
              "state": "pending",
              "isPinned": false,
              "statefulConstraints": [
                {
                  "type": "manual-judgement",
                  "status": "NOT_EVALUATED"
                }
              ]
            }
          ],
          "build": {
            "id": 5
          },
          "git": {
            "commit": "46cd7bf"
          }
        },
        {
          "version": "master-h4.ae5d949",
          "displayName": "master-h4.ae5d949",
          "environments": [
            {
              "name": "test",
              "state": "pending",
              "isPinned": false,
              "statefulConstraints": [
                {
                  "type": "manual-judgement",
                  "status": "NOT_EVALUATED"
                }
              ]
            }
          ],
          "build": {
            "id": 4
          },
          "git": {
            "commit": "ae5d949"
          }
        }
      ]
    }
  ],
  "environments": [
    {
      "name": "test",
      "artifacts": [
        {
          "name": "spkr/mddemo-titus",
          "type": "docker",
          "reference": "mddemo-titus",
          "statuses": [],
          "versions": {
            "deploying": "master-h19.fa3d725",
            "pending": [
              "master-h5.46cd7bf",
              "master-h4.ae5d949"
            ],
            "approved": [],
            "previous": [
              "master-h18.fa3d725",
              "master-h17.fa3d725",
              "master-h16.fa3d725",
              "master-h15.0a3ef3e",
              "master-h14.8cabcd6",
              "master-h13.53888a8",
              "master-h12.1100b8b",
              "master-h11.1100b8b",
              "master-h10.96eef56",
              "master-h9.8377d7a",
              "master-h8.930f489",
              "master-h7.390b218",
              "master-h6.63e586e"
            ],
            "vetoed": [
              "master-h20.fa3d725"
            ],
            "skipped": []
          }
        }
      ],
      "resources": [
        "titus:cluster:titustestvpc:lpollomdtest-test"
      ]
    }
  ]
}
```
</details>

There's only one delivery config in the DB, still associated with the original app:
| uid	| name | application | service_account | api_version |
| --- | --- | --- | --- | --- |
| 01E0H5YZY66WZVVW7QKYQ3NVEG | mddemotitus | mddemotitus | delivery-engineering@netflix.com | delivery.config.spinnaker.netflix.com/v1 |

### PR DESCRIPTION
**Pull request by gal-yardeni**
closes #1260 .

The delivery config name should be unique across all applications. 
This PR preventing the following:
- delivery config with name "config" and application "app1" is already persisted.
- someone is trying to submit a config with name "config", for application "app2".
- "app1" and "app2" have at least one same resource.

If app1 and app2 somehow have the same resources (like in the bug description), both apps are entering a weird state.

### CODE REVIEW

File: keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CombinedRepository.kt [hunk 1]
```diff
@@ -81,26 +81,31 @@ class CombinedRepository(
 
   @Transactional(propagation = REQUIRED)
   override fun upsertDeliveryConfig(deliveryConfig: DeliveryConfig): DeliveryConfig {
-    val old = try {
+    val configWithSameName = try {
```
Comment (gal-yardeni) [inline keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CombinedRepository.kt:84]: Renamed some variables, let me know if it makes sense..

File: keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CombinedRepositoryTests.kt [hunk 2]
```diff
@@ -317,5 +335,33 @@ abstract class CombinedRepositoryTests<D : DeliveryConfigRepository, R : Resourc
...
+        expectThrows<DuplicateDeliveryConfigsException> { subject.upsertDeliveryConfig(anotherDeliveryConfigWithSameName) }
+        expectThat(deliveryConfigRepository.get(configName))
+          .get { application }
+          .isEqualTo(deliveryConfig.application)
+
+        expectThrows<NoSuchDeliveryConfigException> { deliveryConfigRepository.getByApplication(anotherDeliveryConfigWithSameName.application) }
+      }
+    }
+
+    context("an application cannot have more than a single config") {
```
Comment (gal-yardeni) [inline keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CombinedRepositoryTests.kt:353]: Added a test for `TooManyDeliveryConfigs` as well.

File: keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CombinedRepositoryTests.kt [hunk 3]
```diff
@@ -317,5 +335,33 @@ abstract class CombinedRepositoryTests<D : DeliveryConfigRepository, R : Resourc
         expectCatching { resourceRepository.get(firstResource.id) }.isSuccess()
       }
     }
+
+    context("don't allow storing delivery config with a non unique name") {
+      before {
+        subject.upsertDeliveryConfig(deliveryConfig)
+      }
+      test("trying to persist another config with the same name but different application") {
```
Comment (luispollo) [inline keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CombinedRepositoryTests.kt:343]: I think this should be the description of your `context` above. The `test` here is testing that trying to persist the delivery config `"throws a DuplicateDeliveryConfigsException"`.

File: keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CombinedRepositoryTests.kt [hunk 4]
```diff
@@ -317,5 +335,33 @@ abstract class CombinedRepositoryTests<D : DeliveryConfigRepository, R : Resourc
...
+
+        expectThrows<NoSuchDeliveryConfigException> { deliveryConfigRepository.getByApplication(anotherDeliveryConfigWithSameName.application) }
+      }
+    }
+
+    context("an application cannot have more than a single config") {
+      before {
+        subject.upsertDeliveryConfig(deliveryConfig)
+      }
+      test("trying to persist another config with the same application but different config names") {
```
Comment (luispollo) [inline keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CombinedRepositoryTests.kt:357]: Same comment on the context vs. test descriptions.

File: keel-core/src/main/kotlin/com/netflix/spinnaker/keel/exceptions/DuplicateManagedResourceException.kt [hunk 5]
```diff
@@ -6,5 +6,5 @@ class DuplicateManagedResourceException(
   newConfig: String
 ) : ValidationException(
   "Resource with id $id exist in a delivery config named ($existingConfig). " +
-    "Please ensure to remove reousrce $id from config named $existingConfig, if you wish this resource to be managed in $newConfig."
+    "Please ensure to remove resource $id from config named $existingConfig, if you wish this resource to be managed in $newConfig."
```
Comment (luispollo) [inline keel-core/src/main/kotlin/com/netflix/spinnaker/keel/exceptions/DuplicateManagedResourceException.kt:9]: Good spot! 🙂

File: keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CombinedRepository.kt [hunk 6]
```diff
@@ -81,26 +81,31 @@ class CombinedRepository(
...
       getDeliveryConfig(deliveryConfig.name)
     } catch (e: NoSuchDeliveryConfigException) {
       null
     }
 
-    val existingConfig = try {
+    if (configWithSameName != null && configWithSameName.application != deliveryConfig.application) {
+      // we don't allow storing 2 configs with the same name, for different applications
+      throw DuplicateDeliveryConfigsException(configWithSameName.application)
```
Comment (luispollo) [inline keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CombinedRepository.kt:92]: I think a better name for this exception might be `ConflictingDeliveryConfigsException`.

File: keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CombinedRepository.kt (hunk 1 above)
Comment (luispollo) [reply keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CombinedRepository.kt:84]: The names are a bit long, but definitely more self-explanatory than the previous ones, so I think they're ok. The only thought that occurred to me is whether we might be over-complicating things unnecessarily given the constraint we want to enforce. Specifically, since each app can only have one delivery config, what's the point of having the user specify a name for the delivery config in the first place? We could just index on the app name... But the problem with changing that is that we'd need to go around and fix everyone's delivery configs, so I'm discouraged for that reason...

Comment (lorin) [reply keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CombinedRepository.kt:84]: @luispollo One thing we could do is make the delivery config name optional (under the hood we could just default the delivery config name to the app name), and "deprecate" the use of a delivery config name. This would avoid breaking existing users.

Comment (gal-yardeni) [reply keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CombinedRepository.kt:84]: Yeah, I see what you are saying. Fwiw, I think 99% of our users will not even specify the delivery config name, so I believe we won't really hit issues regarding config names anymore. I hope this is the last fix in that space!

Comment (gal-yardeni) [reply keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CombinedRepository.kt:84]: @lorin delivery config names are optional, and they are defaulting to "appName-manifest".

Comment (lorin) [reply keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CombinedRepository.kt:84]: @gal-yardeni I didn't realize that! I think we should eventually stop letting people give their delivery configs custom names.

Comment (gal-yardeni) [reply keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CombinedRepository.kt:84]: @lorin I'm on the fence about it :) we can raise this question to the team.

Comment (robfletcher) [reply keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CombinedRepository.kt:84]: The problem with that would be that it bakes in the one-config-per-app constraint that we're not sure we want in the long term.
