### PR TITLE
fix(clouddriver): switch to async cache

### LINKED ISSUE #1141: Instances stuck with high CPU utilization
We saw two out of four instances stop making resource checks, both report very high CPU utilization:

<details>
<summary>CPU graph</summary>

image
</details>

Flame graph ([flamegraph.zip](https://github.com/spinnaker/keel/files/4596343/flamegraph.zip)) shows the stuck instances spending their time in ConcurrentHashMap code:

image

[Complete thread dump gist](https://gist.github.com/lorin/e9919ca28e7a521168acfc49e668450f), relevant stack trace below:

<details>
<summary>relevant thread dump</summary>

```
"https-jsse-nio-7002-exec-9 @coroutine#66311" #68 daemon prio=5 os_prio=0 tid=0x00007efdd29d5000 nid=0x119d runnable [0x00007efd79958000]
   java.lang.Thread.State: RUNNABLE
	at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1934)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2377)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2360)
	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:108)
	at com.github.benmanes.caffeine.cache.LocalManualCache.get(LocalManualCache.java:62)
	at com.netflix.spinnaker.keel.clouddriver.MemoryCloudDriverCache.getOrNotFound(MemoryCloudDriverCache.kt:136)
	at com.netflix.spinnaker.keel.clouddriver.MemoryCloudDriverCache.securityGroupById(MemoryCloudDriverCache.kt:71)
	at com.netflix.spinnaker.keel.ec2.resource.ClusterHandler.getSecurityGroupNames(ClusterHandler.kt:965)
	at com.netflix.spinnaker.keel.ec2.resource.ClusterHandler.toServerGroup(ClusterHandler.kt:855)
	at com.netflix.spinnaker.keel.ec2.resource.ClusterHandler.access$toServerGroup(ClusterHandler.kt:85)
	at com.netflix.spinnaker.keel.ec2.resource.ClusterHandler$getServerGroups$5$invokeSuspend$$inlined$map$lambda$1.invokeSuspend(ClusterHandler.kt:808)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:272)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:79)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at com.netflix.spinnaker.keel.clouddriver.MemoryCloudDriverCache$getOrNotFound$1.apply(MemoryCloudDriverCache.kt:138)
	at com.netflix.spinnaker.keel.clouddriver.MemoryCloudDriverCache$getOrNotFound$1.apply(MemoryCloudDriverCache.kt:31)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2379)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache$$Lambda$947/1743548301.apply(Unknown Source)
	at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1853)
	- locked <0x0000000731962820> (a java.util.concurrent.ConcurrentHashMap$ReservationNode)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2377)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2360)
	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:108)
	at com.github.benmanes.caffeine.cache.LocalManualCache.get(LocalManualCache.java:62)
	at com.netflix.spinnaker.keel.clouddriver.MemoryCloudDriverCache.getOrNotFound(MemoryCloudDriverCache.kt:136)
	at com.netflix.spinnaker.keel.clouddriver.MemoryCloudDriverCache.securityGroupById(MemoryCloudDriverCache.kt:71)
	at com.netflix.spinnaker.keel.ec2.resource.ClusterHandler.getSecurityGroupNames(ClusterHandler.kt:965)
	at com.netflix.spinnaker.keel.ec2.resource.ClusterHandler.toServerGroup(ClusterHandler.kt:855)
	at com.netflix.spinnaker.keel.ec2.resource.ClusterHandler.access$toServerGroup(ClusterHandler.kt:85)
	at com.netflix.spinnaker.keel.ec2.resource.ClusterHandler$getServerGroups$5$invokeSuspend$$inlined$map$lambda$1.invokeSuspend(ClusterHandler.kt:808)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:272)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:79)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at com.netflix.spinnaker.keel.clouddriver.MemoryCloudDriverCache$getOrNotFound$1.apply(MemoryCloudDriverCache.kt:138)
	at com.netflix.spinnaker.keel.clouddriver.MemoryCloudDriverCache$getOrNotFound$1.apply(MemoryCloudDriverCache.kt:31)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2379)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache$$Lambda$947/1743548301.apply(Unknown Source)
	at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1853)
	- locked <0x00000007319627c0> (a java.util.concurrent.ConcurrentHashMap$ReservationNode)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2377)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2360)
	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:108)
	at com.github.benmanes.caffeine.cache.LocalManualCache.get(LocalManualCache.java:62)
	at com.netflix.spinnaker.keel.clouddriver.MemoryCloudDriverCache.getOrNotFound(MemoryCloudDriverCache.kt:136)
	at com.netflix.spinnaker.keel.clouddriver.MemoryCloudDriverCache.securityGroupById(MemoryCloudDriverCache.kt:71)
	at com.netflix.spinnaker.keel.ec2.resource.ClusterHandler.getSecurityGroupNames(ClusterHandler.kt:965)
	at com.netflix.spinnaker.keel.ec2.resource.ClusterHandler.toServerGroup(ClusterHandler.kt:855)
	at com.netflix.spinnaker.keel.ec2.resource.ClusterHandler.access$toServerGroup(ClusterHandler.kt:85)
	at com.netflix.spinnaker.keel.ec2.resource.ClusterHandler$getServerGroups$5$invokeSuspend$$inlined$map$lambda$1.invokeSuspend(ClusterHandler.kt:808)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:272)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:79)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at com.netflix.spinnaker.keel.rest.ExportController.get(ExportController.kt:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:888)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:118)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at com.netflix.spinnaker.fiat.shared.FiatAuthenticationFilter.doFilter(FiatAuthenticationFilter.java:65)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:158)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:108)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.netflix.spinnaker.platform.netflix.security.auth.MetatronAuthenticationFilter.doFilter(MetatronAuthenticationFilter.java:118)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at javax.servlet.FilterChain$doFilter$1.call(Unknown Source)
	at com.netflix.spinnaker.filters.AuthenticatedRequestFilter.doFilter(AuthenticatedRequestFilter.groovy:143)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:367)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:860)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1598)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	- locked <0x000000072a8c7368> (a org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
	- <0x00000006d2f129f0> (a java.util.concurrent.ThreadPoolExecutor$Worker)
```

</details>

### PR DESCRIPTION
**Pull request by lorin**
# Summary

Change the cache objects in MemoryCloudDriverCache to use the Caffeine library's [AsyncCache] to eliminate a race condition.

Fixes #1141

# Background

Keel's [MemoryCloudDriverCache] class uses the [Caffeine] library to implement in-memory caching of the results of calls to clouddriver.

A Caffeine Cache implementation is backed by a Java ConcurrentHashMap. In particular, if you call [Cache.get] and there's a cache miss, the library will ultimately call [ConcurrentHashMap.compute], executing the `mappingFunction` that was passed in as an argument to compute the data on cache miss.

# The problem

The `mappingFunction` used to compute the data on cache miss is not allowed to make additional calls into the same ConcurrentHashMap. From the [docs][ConcurrentHashMap.compute]:

> Some attempted update operations on this map by other threads may be blocked while computation is in progress, so the computation should be short and simple, and must not attempt to update any other mappings of this Map.

In the keel code, we define this mapping function in the [getOrNotFound] method as a lambda, it looks like this:

```
{
  runCatching {
    runBlocking(block = loader) // loader: suspend CoroutineScope.() -> T?
  }
   ... // some other stuff that isn't relevant here
}
```

Because our mapping function yields control back to the coroutine scheduler, we can get into situations where the newly scheduled coroutine ends up calling into the same cache object, which violates the contract of ConcurrentHashMap. (See #1141 for an example stack trace where this happens).

The upshot is that **it's not safe to call suspending kotlin functions from within the second argument to [Cache.get],** because this may result in a recursive call to [ConcurrentHashMap.compute].

# Solution requirements

To fix this, we need to change the calling patterns so that there's no possibility that the mapping function passed to [Cache.get] ends up making calls against the same cache.

# Implemented solution

As [recommended] by @ben-manes, I switched to using Caffeine's [AsyncCache]. This implementation stores and retrieves CompleteableFutures (which stores the mapping function as a [thunk]). Since the cache doesn't execute the mapping function on a cache miss, there's no risk of a recursive call.

Switching to async cache required changing the execution order in the `getOrNotFoundMethod` so that we now "block" after the data is retrieved from the cache (to complete the future), where before we "blocked" inside the mapping function:

## Before

```kotlin
get(key) {
    runCatching {
      runBlocking(block = loader)
    }
    ...
}
```

## After

```kotlin
runCatching {
    runBlocking {
      get(key, asyncify(loader)).await()
    }
  }
```

I added some adapter code to convert between Java 8 CompletableFuture objects and Kotlin coroutines.

[AsyncCache]: https://github.com/ben-manes/caffeine/wiki/Population#asynchronous-manual

[MemoryCloudDriverCache]: https://github.com/spinnaker/keel/blob/949b22245e268c12f15cbbedfcbc1f82de2c0aa7/keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/MemoryCloudDriverCache.kt

[Caffeine]: https://github.com/ben-manes/caffeine/wiki

[Cache.get]: https://www.javadoc.io/doc/com.github.ben-manes.caffeine/caffeine/2.8.0/com/github/benmanes/caffeine/cache/Cache.html

[ConcurrentHashMap.compute]: https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ConcurrentHashMap.html#compute-K-java.util.function.BiFunction-

[getOrNotFound]: https://github.com/spinnaker/keel/blob/949b22245e268c12f15cbbedfcbc1f82de2c0aa7/keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/MemoryCloudDriverCache.kt#L137-L146

[recommended]: https://github.com/spinnaker/keel/issues/1141#issuecomment-625643313

[thunk]: https://en.wikipedia.org/wiki/Thunk

### CODE REVIEW

File: keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/MemoryCloudDriverCache.kt [hunk 1]
```diff
@@ -35,38 +42,51 @@ class MemoryCloudDriverCache(
...
 
   override fun credentialBy(name: String): Credential =
     credentials.getOrNotFound(name, "Credentials with name $name not found") {
       cloudDriver.getCredential(name, DEFAULT_SERVICE_ACCOUNT)
     }
 
+  /**
+   * Convert a value to a [CompletableFuture] so it can be passed to [AsyncCache.put]
+   */
+  private fun <T> futurify(x: T?): CompletableFuture<T?> = CoroutineScope(EmptyCoroutineContext).future { x }
```
Comment (lorin) [inline keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/MemoryCloudDriverCache.kt:80]: Because I don't have a deep understanding of kotlin coroutines, I'm not sure if I'm using right coroutine scope here.

File: keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/MemoryCloudDriverCache.kt [hunk 2]
```diff
@@ -105,15 +125,17 @@ class MemoryCloudDriverCache(
     }
 
   override fun availabilityZonesBy(account: String, vpcId: String, purpose: String, region: String): Set<String> =
```
Comment (lorin) [inline keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/MemoryCloudDriverCache.kt:127]: All of the other functions call the `getOrNotFound` helper method except this one.

File: keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/MemoryCloudDriverCache.kt (hunk 1 above)
Comment (luispollo) [reply keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/MemoryCloudDriverCache.kt:80]: Frankly, I don't think any of us are experts in coroutines. 🙂 

Could you please elaborate on what led you to pick `EmptyCoroutineContext` in this case?

File: keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/MemoryCloudDriverCache.kt [hunk 3]
```diff
@@ -35,38 +42,51 @@ class MemoryCloudDriverCache(
...
+   */
+  private fun <T> futurify(x: T?): CompletableFuture<T?> = CoroutineScope(EmptyCoroutineContext).future { x }
+
+  /**
+   * Convert a suspending function to a [BiFunction] that [AsyncCache.get] expects as its second argument
+   *
+   * Uses [Dispatchers.IO] because it assumes that [block] makes I/O calls
+   */
+  private fun <T> asyncify(block: suspend CoroutineScope.() -> T?): BiFunction<String, Executor, CompletableFuture<T?>> =
+    BiFunction { _: String, _: Executor -> CoroutineScope(Dispatchers.IO).future(block = block) }
```
Comment (luispollo) [inline keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/MemoryCloudDriverCache.kt:88]: What's the intent of specifying the types here if you don't use the variables?

Comment (lorin) [reply keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/MemoryCloudDriverCache.kt:88]: They don't really need to be there. They are a remnant of earlier struggles I was having figuring out how to convert from a kotlin closure to a BiFunction. I'll zap them.

File: keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/MemoryCloudDriverCache.kt (hunk 1 above)
Comment (lorin) [reply keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/MemoryCloudDriverCache.kt:80]: The [future] method is defined on a coroutine scope, and TBH I couldn't think of a better option for a coroutine scope to use here. This code just wraps a constant value inside of a future (i.e., all it does is `return x` where x is a known value). My reasoning was to use the simplest possible thing as a wrapper, and `EmptyCoroutineContext` sounded simplest. 

I could also avoid coroutines entirely and use the [supplyAsync] method:

```
private fun <T> futurify(x: T?): CompletableFuture<T?> = applyAsync {x}
```

But when I read the description of that method, it sounds like it will execute the lambda inside of a threadpool, which is OK, but seems wasteful to do a thread context switch instead of a coroutine context switch.

[future]: https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-jdk8/kotlinx.coroutines.future/kotlinx.coroutines.-coroutine-scope/future.html

[supplyAsync]: https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CompletableFuture.html#supplyAsync-java.util.function.Supplier-

**Comment by lorin** [comment]
> The only bit I was unsure about was your choice for the coroutine scope in futurify, but without further context I can't say whether this is the wrong choice, so I'm giving you a vote on a confidence on that one. 🙂

Yeah, that's the part of this PR I have the least confidence in. I don't really know how else to increase confidence other than deploy it to prestaging and see whether it behaves the way it should.

> Given that this added a bit of complexity to the implementation and that it was a non-trivial problem, I think it might be useful to add a comment in this class with a summary explaining why we're using the async approach.

That's a good idea, I'll do that.

File: keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/MemoryCloudDriverCache.kt (hunk 1 above)
Comment (ben-manes) [reply keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/MemoryCloudDriverCache.kt:80]: what about `CompletableFuture.completedFuture(x)`?

Comment (ben-manes) [reply keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/MemoryCloudDriverCache.kt:80]: if this is for `AsyncCache.put(key, future)` per comment, then you can use the `synchronous()` view's `put(key, value)`, which does `put(key, completedFuture(value))`

Comment (lorin) [reply keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/MemoryCloudDriverCache.kt]: > if this is for `AsyncCache.put(key, future)` per comment, then you can use the `synchronous()` view's `put(key, value)`, which does `put(key, completedFuture(value))`

Yup, this is what it's for. I switched to using `synchronous().put(...)` in 83982e61.

File: keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/MemoryCloudDriverCache.kt (hunk 3 above)
Comment (lorin) [reply keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/MemoryCloudDriverCache.kt]: Zapped in 83982e61

**Comment by luispollo** [comment]
@lorin FWIW, I took another look and the changes you made based on @ben-manes' feedback look good to me.

File: keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/MemoryCloudDriverCache.kt [hunk 4]
```diff
@@ -15,58 +15,81 @@
...
 
   override fun credentialBy(name: String): Credential =
     credentials.getOrNotFound(name, "Credentials with name $name not found") {
       cloudDriver.getCredential(name, DEFAULT_SERVICE_ACCOUNT)
     }
 
+  /**
+   * Convert a suspending function to a [BiFunction] that [AsyncCache.get] expects as its second argument
+   *
+   * Uses [Dispatchers.IO] because it assumes that [block] makes I/O calls
```
Comment (robfletcher) [inline keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/MemoryCloudDriverCache.kt:88]: To the best of my understanding this is right. The cache will be primed by HTTP calls to CloudDriver.

File: keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/MemoryCloudDriverCache.kt [hunk 5]
```diff
@@ -105,15 +128,17 @@ class MemoryCloudDriverCache(
...
+      availabilityZones.get("$account:$vpcId:$purpose:$region",
+        asyncify {
+          cloudDriver
+            .listSubnets("aws", DEFAULT_SERVICE_ACCOUNT)
+            .filter { it.account == account && it.vpcId == vpcId && it.purpose == purpose && it.region == region }
+            .map { it.availabilityZone }
+            .toSet()
+        }
+      ).await()
+    }
```
Comment (robfletcher) [inline keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/MemoryCloudDriverCache.kt:141]: Do we have to wrap the initial cache attempt  with `runBlocking`?

Comment (lorin) [reply keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/MemoryCloudDriverCache.kt:141]: Yeah, the returned value from the cache is now a `CompleteableFuture`, which we call [await] on (line 140). `await` is a suspend function, so it needs to bre wrapped.

[await]: https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-jdk8/kotlinx.coroutines.future/java.util.concurrent.-completion-stage/await.html
