### PR TITLE
fix(sql): Cascade deletion of delivery config to event and paused records

### LINKED ISSUE #1467: Deleting delivery config does not cleanup related records
While testing with a delivery config I had to delete/recreate, I noticed the corresponding records from the following tables are not deleted:
- `artifact_versions`
- `diff_fingerprint`
- `event` (I forget if this was by design or not)
- `resource_last_checked`
- `unhappy_veto`

Cc: @emjburns

### PR DESCRIPTION
**Pull request by luispollo**
Complements #1660 to close #1467.

### CODE REVIEW

File: keel-core/src/main/kotlin/com/netflix/spinnaker/keel/events/PersistentEvent.kt [hunk 1]
```diff
@@ -29,7 +29,7 @@ abstract class PersistentEvent {
     val clock: Clock = Clock.systemUTC()
   }
 
-  enum class Scope {
+  enum class EventScope {
```
Comment (luispollo) [inline keel-core/src/main/kotlin/com/netflix/spinnaker/keel/events/PersistentEvent.kt:32]: Renamed this to avoid confusion with other "scopes" in the codebase.

File: keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlDeliveryConfigRepository.kt [hunk 2]
```diff
@@ -184,6 +210,15 @@ class SqlDeliveryConfigRepository(
...
     }
 
+  private fun getResourceIDs(application: String): List<String> =
+    sqlRetry.withRetry(READ) {
+      jooq
+        .select(RESOURCE.ID)
+        .from(RESOURCE)
+        .where(RESOURCE.APPLICATION.eq(application))
+        .fetch(RESOURCE.ID)
+    }
```
Comment (robfletcher) [inline keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlDeliveryConfigRepository.kt:220]: Seems to me it would be pretty easy to inline this into the queries and delete everything at once rather than having to do a `forEach` over all the resources

File: keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/DeliveryConfigRepositoryTests.kt [hunk 3]
```diff
@@ -201,33 +238,7 @@ abstract class DeliveryConfigRepositoryTests<T : DeliveryConfigRepository, R : R
...
-                  ManualJudgementConstraint()
-                ),
-                resources = setOf(
-                  resource(kind = parseKind("ec2/cluster@v1")),
-                  resource(kind = parseKind("ec2/security-group@v1"))
-                )
-              )
-            )
-          )
+          deliveryConfig = completeDeliveryConfig
```
Comment (robfletcher) [inline keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/DeliveryConfigRepositoryTests.kt:241]: What's the thinking behind making this a top-level val? It seems to only be used here.

File: keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlDeliveryConfigRepository.kt (hunk 2 above)
Comment (luispollo) [reply keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlDeliveryConfigRepository.kt:220]: Ya, good point. I just got lazy and followed the pattern. Will change it!

File: keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/DeliveryConfigRepositoryTests.kt (hunk 3 above)
Comment (luispollo) [reply keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/DeliveryConfigRepositoryTests.kt:241]: I kept this change by accident. Was planning on using that elsewhere and never did. Will undo.

File: keel-sql/src/main/resources/db/changelog/20201203-cleanup-event-and-paused-orhpans.yml [hunk 4]
```diff
@@ -0,0 +1,25 @@
+databaseChangeLog:
+- changeSet:
```
Comment (luispollo) [inline keel-sql/src/main/resources/db/changelog/20201203-cleanup-event-and-paused-orhpans.yml:2]: Cleans up any existing orphan records from the database.

File: keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlDeliveryConfigRepository.kt [hunk 5]
```diff
@@ -166,31 +188,28 @@ class SqlDeliveryConfigRepository(
         .fetchOne(DELIVERY_CONFIG.UID)
     } ?: throw NoDeliveryConfigForApplication(application)
 
-  private fun getEnvironmentUIDs(deliveryConfigUIDs: List<String>): List<String> =
+  private fun getResourceUIDs(application: String): SelectConditionStep<Record1<String>>? =
     sqlRetry.withRetry(READ) {
```
Comment (robfletcher) [inline keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlDeliveryConfigRepository.kt:192]: It doesn't make sense to have a retry in here if this is returning the query itself rather than executing it

Comment (luispollo) [reply keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlDeliveryConfigRepository.kt:192]: True. Will fix.

File: keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlDeliveryConfigRepository.kt [hunk 6]
```diff
@@ -166,31 +188,28 @@ class SqlDeliveryConfigRepository(
...
       jooq
-        .select(ENVIRONMENT.UID)
```
Comment (robfletcher) [inline keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlDeliveryConfigRepository.kt:172]: You also don't need to call this on a `DSLContext` instance, there's a static function `DSL.select` you can use when you want to create a sub-query like this.

Comment (luispollo) [reply keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlDeliveryConfigRepository.kt]: Yeah, but it doesn't hurt, does it?

**Comment by luispollo** [comment]
@robfletcher I think I've addressed your feedback. Anything else you'd like to see changed before approving?

**Review by robfletcher — APPROVED** [review]
